#!/usr/bin/env bash
# tests/run-all-tests-roster/test-runner-roster-integrity.sh — proves that
# tests/run-all-tests.sh executes every suite it discovered, and that when it
# does not, it says so loudly instead of printing RESULT: ALL PASS.
#
# Why this exists: the orchestrator used to feed its discovery list through
# its own stdin (`while read ... done < <(find ...)`) while starting each
# suite with that same stdin still attached. Any suite that read stdin — most
# often by accident, e.g. a `grep -qF "-589" "$LOG"` whose needle was parsed
# as a grep option so grep lost its file operand and fell back to stdin —
# swallowed the remaining suite paths. The loop ended immediately, and the
# run reported RESULT: ALL PASS having executed 12 of 88 suites. A human who
# happened to remember the baseline of 88 was the only detector.
#
# Two defences are under test here and each is exercised against a real,
# mutated copy of the production runner rather than a re-implementation:
#   (1) every suite is started with stdin closed, so it cannot drain the list;
#   (2) the roster reconciliation — discovered + registered extras must equal
#       ran + skipped + missing — which catches truncation from ANY cause,
#       including ones nobody has thought of yet.
#
# CHAIN: none. PRIME_DIRECTIVE: safe — no broadcast, no network, no SSH, no
#        notification. Every case builds a disposable fixture repo under a
#        mktemp dir (its own tests/ tree, its own copy of the runner) and
#        runs that copy. This host's real tests/ tree is never executed and
#        never modified. The fixture runner does perform the production
#        preflight against the real PATH, so this suite inherits the same
#        python3/JSON-schema-validator requirement as the aggregate run
#        itself — a host that cannot satisfy the preflight cannot run the
#        aggregate either.
#
# Coverage:
#   1. static: the production runner still closes stdin on BOTH suite
#      invocation paths (verbose and captured).
#   2. fixed runner + a stdin-eating suite: all 7 discovered fixture suites
#      execute, roster reconciles, RESULT: ALL PASS, rc 0.
#   3. MUTANT (stdin redirect removed — the historical shape): the run
#      truncates to a single discovered suite, the roster mismatch fires,
#      RESULT: ALL PASS is NOT printed, rc != 0. This is the before/after
#      pair that proves case 2 is actually exercising the defect.
#   4. MUTANT (a discovered suite silently dropped for an unrelated reason):
#      the roster mismatch fires on a truncation route that has nothing to do
#      with stdin — proving defence (2) is general, not a second spelling of
#      defence (1).
#   5. a registered extra suite that is absent from disk keeps the arithmetic
#      balanced (it is named in the `missing` bucket) AND still turns the run
#      red. Every registered extra is git-tracked, so `missing` always means
#      the aggregate silently shrank; balancing the books is not consent.
#  5b. MUTANT (the missing>0 check disabled): the same fixture goes green
#      again — proving that check is what creates the red, not some other
#      incidental failure in the fixture.
#   6. host SKIP (Linux-only extra) is accounted for, not silently dropped.
#   7. discovery that finds nothing is a hard refusal (rc 2), not an empty
#      green run — under the default pattern AND a caller-supplied one.
#   8. every mutation asserts its own target was found before running, so a
#      future reformat of the runner turns this suite red instead of quietly
#      testing an unmutated copy.
#
# Usage:
#   bash tests/run-all-tests-roster/test-runner-roster-integrity.sh
#
# Exit codes:
#   0  all cases PASS
#   1  any case FAILED

set -u

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
REAL_RUNNER="${REPO_ROOT}/tests/run-all-tests.sh"

if [ ! -f "$REAL_RUNNER" ]; then
	echo "FATAL: runner not found at $REAL_RUNNER" >&2
	exit 1
fi

PASS=0
FAIL=0
pass() { printf 'PASS  %-72s\n' "$1"; PASS=$((PASS + 1)); }
fail() { printf 'FAIL  %-72s\n' "$1" >&2; FAIL=$((FAIL + 1)); }

TMP="$(mktemp -d -t runner-roster-test.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

# Number of glob-discoverable suites each fixture repo gets. The first one
# is the stdin eater; the rest are inert.
FIXTURE_SUITES=7

# =====================================================================
# helpers
# =====================================================================

# write_suite <path> <marker-path> [eat]
# Generates a disposable bash suite that records the fact it ran by touching
# <marker-path>. With "eat" it first drains stdin to EOF — the behaviour the
# whole defect turns on.
write_suite() {
	{
		printf '%s\n' '#!/usr/bin/env bash'
		printf '%s\n' '# disposable fixture suite — generated by test-runner-roster-integrity.sh'
		if [ "${3:-}" = "eat" ]; then
			printf '%s\n' '# Drains stdin. Stands in for any suite that reads stdin, deliberately'
			printf '%s\n' '# or by accident (grep losing its file operand to a "-NUM" needle).'
			printf '%s\n' 'cat >/dev/null'
		fi
		printf ': > %s\n' "'$2'"
		printf '%s\n' 'exit 0'
	} > "$1"
	chmod +x "$1"
}

# build_fixture <case-dir>
# Lays out a miniature repo whose shape matches what the runner expects:
#   tests/fixture/test-NN.sh          -> glob-discovered (FIXTURE_SUITES of them)
#   tests/cycle-gate/run-tests.sh     -> EXTRA_SUITES member
#   scripts/operator-local/...        -> EXTRA_SUITES member (outside tests/)
#   tests/ops/test_b6_enable_cron.py  -> EXTRA_SUITES_OTHER member (python3)
#   tests/anomalies/integration-linux.sh -> Linux-only extra
# None of the extras match the test-*.sh glob under tests/, exactly as in the
# real repo, so "discovered" stays cleanly separable from "registered".
build_fixture() {
	local case_dir="$1" repo markers i name
	repo="$case_dir/repo"
	markers="$case_dir/markers"
	mkdir -p "$repo/tests/fixture" "$repo/tests/cycle-gate" "$repo/tests/ops" \
		"$repo/tests/anomalies" "$repo/scripts/operator-local" "$markers"

	i=1
	while [ "$i" -le "$FIXTURE_SUITES" ]; do
		name="$(printf 'test-%02d.sh' "$i")"
		if [ "$i" -eq 1 ]; then
			name="test-01-stdin-eater.sh"
			write_suite "$repo/tests/fixture/$name" "$markers/suite-$name" eat
		else
			write_suite "$repo/tests/fixture/$name" "$markers/suite-$name"
		fi
		i=$((i + 1))
	done

	write_suite "$repo/tests/cycle-gate/run-tests.sh" "$markers/extra-cycle-gate"
	write_suite "$repo/scripts/operator-local/test-commit-anchor-source.sh" "$markers/extra-operator-local"
	write_suite "$repo/tests/anomalies/integration-linux.sh" "$markers/extra-integration-linux"

	{
		printf '%s\n' '#!/usr/bin/env python3'
		printf '%s\n' '# disposable fixture suite — generated by test-runner-roster-integrity.sh'
		printf 'open(%s, "w").close()\n' "'$markers/extra-b6-python'"
		printf '%s\n' 'print("Ran 1 test in 0.000s")'
	} > "$repo/tests/ops/test_b6_enable_cron.py"

	cp "$REAL_RUNNER" "$repo/tests/run-all-tests.sh"
	chmod +x "$repo/tests/run-all-tests.sh"
}

# apply_mutation <file> <needle> <replacement>
# Literal (non-regex) whole-file replacement. Returns 3 — and therefore fails
# the calling case — when the needle is absent, so a reformatted runner can
# never leave this suite silently testing an unmutated copy.
apply_mutation() {
	local f="$1" needle="$2" repl="$3" content
	content="$(cat "$f")"
	case "$content" in
		*"$needle"*) ;;
		*) return 3 ;;
	esac
	printf '%s\n' "${content//"$needle"/$repl}" > "$f"
}

# count_markers <markers-dir> <prefix>
count_markers() {
	local n=0 f
	for f in "$1/$2"*; do
		[ -e "$f" ] && n=$((n + 1))
	done
	echo "$n"
}

# roster_field <runner-output> <field-name>
# Pulls one integer out of the runner's ROSTER: accounting line.
roster_field() {
	printf '%s\n' "$1" \
		| grep '^ROSTER:' \
		| head -1 \
		| tr -c 'a-zA-Z0-9=-' '\n' \
		| grep -x -- "$2=[0-9][0-9]*" \
		| head -1 \
		| sed 's/^.*=//'
}

# Mutation targets, spelled exactly as they appear in the runner.
# $'...' keeps the tabs literal without expanding $interpreter / $test_file.
M_STDIN_VERBOSE_FROM=$'\t\t"$interpreter" "$test_file" </dev/null'
M_STDIN_VERBOSE_TO=$'\t\t"$interpreter" "$test_file"'
M_STDIN_QUIET_FROM='out="$("$interpreter" "$test_file" </dev/null 2>&1)"'
M_STDIN_QUIET_TO='out="$("$interpreter" "$test_file" 2>&1)"'
M_DROP_FROM=$'\trun_suite "$test_file"\ndone < "$DISCOVERY_LIST"'
M_DROP_TO=$'\tcase "$test_file" in *test-03*) continue ;; esac\n\trun_suite "$test_file"\ndone < "$DISCOVERY_LIST"'
M_MISSING_FROM='if [ "$SUITES_MISSING" -gt 0 ]; then'
M_MISSING_TO='if false; then # MUTANT: missing-suite check disabled'

# On Linux the Linux-only extra runs and nothing is skipped; elsewhere it is
# announced as a SKIP. Both are legitimate — what must never differ is that
# the arithmetic balances and the suite is named either way.
if [ "$(uname)" = "Linux" ]; then
	EXPECT_SKIPPED=0
	EXPECT_EXTRAS_RUN=4
else
	EXPECT_SKIPPED=1
	EXPECT_EXTRAS_RUN=3
fi

# =====================================================================
# case 1 — static: the production runner still closes stdin on both
# invocation paths. Cheap tripwire that names the property directly.
# =====================================================================
if grep -qF -- '"$interpreter" "$test_file" </dev/null' "$REAL_RUNNER"; then
	pass "case1: runner closes stdin on the --verbose suite invocation"
else
	fail "case1: --verbose suite invocation no longer redirects stdin from /dev/null"
fi
if grep -qF -- 'out="$("$interpreter" "$test_file" </dev/null 2>&1)"' "$REAL_RUNNER"; then
	pass "case1: runner closes stdin on the captured suite invocation"
else
	fail "case1: captured suite invocation no longer redirects stdin from /dev/null"
fi

# =====================================================================
# case 2 — the fix: a stdin-eating suite no longer truncates the run.
# =====================================================================
C2="$TMP/case2"; build_fixture "$C2"
OUT2="$(bash "$C2/repo/tests/run-all-tests.sh" 2>&1)"; RC2=$?
RAN2="$(count_markers "$C2/markers" suite-)"
EXTRAS2="$(count_markers "$C2/markers" extra-)"

if [ "$RAN2" -eq "$FIXTURE_SUITES" ]; then
	pass "case2: all $FIXTURE_SUITES discovered suites executed despite the stdin eater"
else
	fail "case2: only $RAN2 of $FIXTURE_SUITES discovered suites executed (truncation still possible)"
fi
if [ "$EXTRAS2" -eq "$EXPECT_EXTRAS_RUN" ]; then
	pass "case2: $EXPECT_EXTRAS_RUN registered extra suite(s) executed"
else
	fail "case2: $EXTRAS2 extra suites executed, expected $EXPECT_EXTRAS_RUN"
fi
if [ "$RC2" -eq 0 ]; then
	pass "case2: fixture run exits 0"
else
	fail "case2: fixture run exited $RC2: $OUT2"
fi
printf '%s\n' "$OUT2" | grep -q "RESULT: ALL PASS" \
	&& pass "case2: reports RESULT: ALL PASS" \
	|| fail "case2: missing RESULT: ALL PASS (got: $OUT2)"

# The arithmetic itself must be printed and must add up — "total is
# explainable" is the acceptance property, not just "total is big enough".
R2_ROSTER="$(roster_field "$OUT2" roster)"
R2_DISC="$(roster_field "$OUT2" discovered)"
R2_ACC="$(roster_field "$OUT2" accounted)"
R2_RAN="$(roster_field "$OUT2" ran)"
R2_SKIP="$(roster_field "$OUT2" skipped)"
R2_MISS="$(roster_field "$OUT2" missing)"
if [ -n "$R2_ROSTER" ] && [ -n "$R2_ACC" ]; then
	pass "case2: run prints a ROSTER accounting line"
else
	fail "case2: no parseable ROSTER accounting line (got: $OUT2)"
fi
if [ "${R2_ACC:-x}" = "$((${R2_RAN:-0} + ${R2_SKIP:-0} + ${R2_MISS:-0}))" ] \
	&& [ "${R2_ACC:-x}" = "${R2_ROSTER:-y}" ]; then
	pass "case2: roster($R2_ROSTER) = ran($R2_RAN) + skipped($R2_SKIP) + missing($R2_MISS)"
else
	fail "case2: accounting does not balance (roster=$R2_ROSTER ran=$R2_RAN skipped=$R2_SKIP missing=$R2_MISS accounted=$R2_ACC)"
fi
if [ "${R2_DISC:-x}" = "$FIXTURE_SUITES" ]; then
	pass "case2: discovered count ($R2_DISC) is independent of the executing loop"
else
	fail "case2: discovered=$R2_DISC, expected $FIXTURE_SUITES"
fi
if [ "${R2_RAN:-x}" = "$((FIXTURE_SUITES + EXPECT_EXTRAS_RUN))" ]; then
	pass "case2: ran($R2_RAN) matches markers ($RAN2 discovered + $EXTRAS2 extra) left on disk"
else
	fail "case2: ran=$R2_RAN but $RAN2 + $EXTRAS2 suites actually left markers"
fi

# =====================================================================
# case 3 — MUTANT: strip the stdin redirect, i.e. restore the historical
# shape. The same fixture must now truncate, and the runner must refuse to
# call it green. This is the before/after pair for the whole fix.
# =====================================================================
C3="$TMP/case3"; build_fixture "$C3"
MUT3="$C3/repo/tests/run-all-tests.sh"
MUT_OK=1
apply_mutation "$MUT3" "$M_STDIN_VERBOSE_FROM" "$M_STDIN_VERBOSE_TO" \
	|| { fail "case3: mutation target (verbose invocation) not found in the runner — reformatted?"; MUT_OK=0; }
apply_mutation "$MUT3" "$M_STDIN_QUIET_FROM" "$M_STDIN_QUIET_TO" \
	|| { fail "case3: mutation target (captured invocation) not found in the runner — reformatted?"; MUT_OK=0; }

if [ "$MUT_OK" -eq 1 ]; then
	if cmp -s "$REAL_RUNNER" "$MUT3"; then
		fail "case3: mutation produced an identical file — nothing was actually mutated"
	else
		pass "case3: mutation applied (stdin redirect removed from both invocations)"
	fi

	OUT3="$(bash "$MUT3" 2>&1)"; RC3=$?
	RAN3="$(count_markers "$C3/markers" suite-)"

	if [ "$RAN3" -lt "$FIXTURE_SUITES" ]; then
		pass "case3: mutant truncated as predicted — $RAN3 of $FIXTURE_SUITES discovered suites ran"
	else
		fail "case3: mutant ran all $RAN3 suites — the fixture is no longer exercising the defect"
	fi
	if [ "$RAN3" -eq 1 ]; then
		pass "case3: exactly the stdin eater ran; it swallowed the rest of the list"
	else
		fail "case3: expected exactly 1 suite to survive the eater, got $RAN3"
	fi
	if [ "$RC3" -ne 0 ]; then
		pass "case3: mutant run exits non-zero (rc=$RC3) instead of green-over-truncation"
	else
		fail "case3: mutant run exited 0 — a truncated run reported success"
	fi
	printf '%s\n' "$OUT3" | grep -q "RESULT: ALL PASS" \
		&& fail "case3: mutant printed RESULT: ALL PASS over a truncated roster" \
		|| pass "case3: mutant never printed RESULT: ALL PASS"
	printf '%s\n' "$OUT3" | grep -q "ROSTER MISMATCH" \
		&& pass "case3: roster mismatch banner fired loudly" \
		|| fail "case3: no ROSTER MISMATCH banner (got: $OUT3)"
	printf '%s\n' "$OUT3" | grep -q "never ran" \
		&& pass "case3: banner names the shortfall (suites discovered then never run)" \
		|| fail "case3: banner does not explain the shortfall (got: $OUT3)"
fi

# =====================================================================
# case 4 — MUTANT: a discovered suite is dropped for a reason unrelated to
# stdin. Proves the roster check is a general net, not a restatement of the
# stdin fix. Exactly one suite disappears, so the shortfall is exactly one.
# =====================================================================
C4="$TMP/case4"; build_fixture "$C4"
MUT4="$C4/repo/tests/run-all-tests.sh"
if apply_mutation "$MUT4" "$M_DROP_FROM" "$M_DROP_TO"; then
	pass "case4: mutation applied (discovery loop silently drops test-03)"

	OUT4="$(bash "$MUT4" 2>&1)"; RC4=$?
	RAN4="$(count_markers "$C4/markers" suite-)"

	if [ "$RAN4" -eq "$((FIXTURE_SUITES - 1))" ]; then
		pass "case4: exactly one discovered suite was dropped ($RAN4 of $FIXTURE_SUITES ran)"
	else
		fail "case4: expected $((FIXTURE_SUITES - 1)) suites to run, got $RAN4"
	fi
	if [ "$RC4" -ne 0 ]; then
		pass "case4: non-stdin truncation also exits non-zero (rc=$RC4)"
	else
		fail "case4: a silently dropped suite still produced a green run"
	fi
	printf '%s\n' "$OUT4" | grep -q "ROSTER MISMATCH" \
		&& pass "case4: roster mismatch fires on a truncation route unrelated to stdin" \
		|| fail "case4: no ROSTER MISMATCH banner (got: $OUT4)"
	printf '%s\n' "$OUT4" | grep -q "^  1 suite(s) were discovered or registered, then never ran" \
		&& pass "case4: banner reports the exact shortfall of 1" \
		|| fail "case4: banner did not report a shortfall of exactly 1 (got: $OUT4)"
	printf '%s\n' "$OUT4" | grep -q "RESULT: ALL PASS" \
		&& fail "case4: printed RESULT: ALL PASS while one suite never ran" \
		|| pass "case4: never printed RESULT: ALL PASS"
else
	fail "case4: mutation target (discovery loop) not found in the runner — reformatted?"
fi

# =====================================================================
# case 5 — a registered extra that is absent from disk. Two properties that
# must hold TOGETHER:
#   - the arithmetic still balances: absence is a named bucket ("missing"),
#     not a hole, so nothing vanishes unexplained;
#   - and the run is still RED. Every registered extra is git-tracked, so
#     `missing` in CI can only mean a rename or deletion that did not update
#     the array — the aggregate silently got smaller, which is exactly the
#     class of failure this accounting exists to surface. Balancing the books
#     is bookkeeping, not consent. A stderr WARN alone would be buried.
# =====================================================================
C5="$TMP/case5"; build_fixture "$C5"
rm -f "$C5/repo/scripts/operator-local/test-commit-anchor-source.sh"
OUT5="$(bash "$C5/repo/tests/run-all-tests.sh" 2>&1)"; RC5=$?
R5_ROSTER="$(roster_field "$OUT5" roster)"
R5_ACC="$(roster_field "$OUT5" accounted)"
R5_MISS="$(roster_field "$OUT5" missing)"

printf '%s\n' "$OUT5" | grep -q "WARN: extra suite not found" \
	&& pass "case5: absent registered extra is warned about" \
	|| fail "case5: no WARN for the absent registered extra (got: $OUT5)"
if [ "${R5_MISS:-x}" = "1" ]; then
	pass "case5: missing=1 recorded in the accounting"
else
	fail "case5: missing=$R5_MISS, expected 1"
fi
if [ -n "${R5_ROSTER:-}" ] && [ "${R5_ACC:-x}" = "${R5_ROSTER:-y}" ]; then
	pass "case5: accounting still balances with a missing extra (roster=$R5_ROSTER accounted=$R5_ACC)"
else
	fail "case5: accounting broke on a missing extra (roster=$R5_ROSTER accounted=$R5_ACC)"
fi
if [ "$RC5" -eq 3 ]; then
	pass "case5: a missing registered suite turns the run red (rc=3) despite balancing"
else
	fail "case5: run exited $RC5 on a missing registered suite, expected 3: $OUT5"
fi
printf '%s\n' "$OUT5" | grep -q "RESULT: ALL PASS" \
	&& fail "case5: printed RESULT: ALL PASS while a registered suite was absent" \
	|| pass "case5: never printed RESULT: ALL PASS"
printf '%s\n' "$OUT5" | grep -q "REGISTERED SUITE MISSING FROM DISK" \
	&& pass "case5: missing-suite banner fired loudly on stderr" \
	|| fail "case5: no missing-suite banner (got: $OUT5)"
printf '%s\n' "$OUT5" | grep -q "ROSTER MISMATCH" \
	&& fail "case5: reported a roster mismatch — the books DO balance here; the diagnosis must be 'missing', not 'mismatch'" \
	|| pass "case5: diagnosed as missing, not misdiagnosed as a mismatch"

# =====================================================================
# case 5b — MUTANT: disable only the missing>0 check. The identical fixture
# must go green again. Without this control, case 5's red could be coming
# from anything; this pins the red to that specific check.
# =====================================================================
C5B="$TMP/case5b"; build_fixture "$C5B"
rm -f "$C5B/repo/scripts/operator-local/test-commit-anchor-source.sh"
MUT5B="$C5B/repo/tests/run-all-tests.sh"
if apply_mutation "$MUT5B" "$M_MISSING_FROM" "$M_MISSING_TO"; then
	pass "case5b: mutation applied (missing-suite check disabled)"
	OUT5B="$(bash "$MUT5B" 2>&1)"; RC5B=$?
	if [ "$RC5B" -eq 0 ]; then
		pass "case5b: with the check disabled the same fixture is green (rc=0) — the check is what makes case5 red"
	else
		fail "case5b: still exited $RC5B with the check disabled — case5's red is not (only) that check: $OUT5B"
	fi
	printf '%s\n' "$OUT5B" | grep -q "RESULT: ALL PASS" \
		&& pass "case5b: mutant prints RESULT: ALL PASS, isolating the check's effect" \
		|| fail "case5b: mutant did not print RESULT: ALL PASS (got: $OUT5B)"
else
	fail "case5b: mutation target (missing-suite check) not found in the runner — reformatted?"
fi

# =====================================================================
# case 6 — host SKIP accounting. On non-Linux the Linux-only extra must be
# announced AND counted; on Linux it must actually run and skipped must be 0.
# =====================================================================
R2_SKIP_INT="${R2_SKIP:-0}"
if [ "$R2_SKIP_INT" = "$EXPECT_SKIPPED" ]; then
	pass "case6: skipped=$R2_SKIP_INT matches this host ($(uname))"
else
	fail "case6: skipped=$R2_SKIP_INT, expected $EXPECT_SKIPPED on $(uname)"
fi
if [ "$EXPECT_SKIPPED" -gt 0 ]; then
	printf '%s\n' "$OUT2" | grep -q "SKIP: tests/anomalies/integration-linux.sh" \
		&& pass "case6: the skipped Linux-only suite is still named in the output" \
		|| fail "case6: Linux-only suite vanished from the output instead of being announced"
else
	[ -e "$C2/markers/extra-integration-linux" ] \
		&& pass "case6: the Linux-only suite actually ran on this Linux host" \
		|| fail "case6: Linux-only suite neither ran nor was announced as skipped"
fi

# =====================================================================
# case 7 — discovery that finds nothing is a hard refusal, not an empty green
# run. Zero discovered reconciles perfectly with zero executed, so the
# arithmetic can never catch this one; only an explicit floor can. Holds for
# the default pattern and for a caller-supplied --pattern alike — "it matched
# nothing" is not a pass under either.
# =====================================================================
C7="$TMP/case7"; build_fixture "$C7"
rm -f "$C7/repo/tests/fixture/"test-*.sh
OUT7="$(bash "$C7/repo/tests/run-all-tests.sh" 2>&1)"; RC7=$?
if [ "$RC7" -eq 2 ]; then
	pass "case7: zero-discovery under the default pattern refuses with rc=2"
else
	fail "case7: zero-discovery exited $RC7, expected 2: $OUT7"
fi
printf '%s\n' "$OUT7" | grep -q "discovered zero suites" \
	&& pass "case7: refusal names broken discovery as the cause" \
	|| fail "case7: missing zero-discovery message (got: $OUT7)"
printf '%s\n' "$OUT7" | grep -q "RESULT: ALL PASS" \
	&& fail "case7: an empty run reported RESULT: ALL PASS" \
	|| pass "case7: an empty run never reported RESULT: ALL PASS"

# Same floor under a caller-supplied pattern, on a repo whose suites all
# still exist — only the glob matches nothing.
C7B="$TMP/case7b"; build_fixture "$C7B"
OUT7B="$(bash "$C7B/repo/tests/run-all-tests.sh" --pattern='zzz-no-such-suite-*.sh' 2>&1)"; RC7B=$?
if [ "$RC7B" -eq 2 ]; then
	pass "case7b: zero-discovery under a caller-supplied --pattern also refuses with rc=2"
else
	fail "case7b: custom-pattern zero-discovery exited $RC7B, expected 2: $OUT7B"
fi
printf '%s\n' "$OUT7B" | grep -q "RESULT: ALL PASS" \
	&& fail "case7b: an empty custom-pattern run reported RESULT: ALL PASS" \
	|| pass "case7b: an empty custom-pattern run never reported RESULT: ALL PASS"

# ---- summary -----------------------------------------------------------------
echo
echo "----------------------------------------"
echo "test-runner-roster-integrity.sh summary: PASS=$PASS  FAIL=$FAIL"
if [ "$FAIL" -gt 0 ]; then
	echo "RESULT: FAIL"
	exit 1
fi
echo "RESULT: PASS"
exit 0
