#!/usr/bin/env bash
# check-identity-pins.sh — detect when the SIGNED artifact_manifest pins in
# public/api/identity.json stop describing reality.
#
# CHAIN: none — reads local files (--mode=repo) or performs read-only HTTP
#        GETs of public URLs (--mode=live). No broadcast, no push, no write
#        to any published artifact.
# PRIME_DIRECTIVE: TESTNET-FIRST — this script has no broadcast pathway.
#
# ---------------------------------------------------------------------------
# Why this exists
# ---------------------------------------------------------------------------
# identity.json carries an `artifact_manifest` object that pins the sha256 of
# every published artifact, and the whole manifest is ed25519-signed by the
# operator. The signature therefore asserts "these bytes are what we publish".
#
# On 2026-08-06 a measurement of the live site found 4 of the 8 pins already
# wrong, two days after the manifest was signed (90bcdd9, 2026-08-04):
#
#   evidence_json.sha256               ✗   push-owned stream
#   validator_json.sha256              ✗   push-owned stream
#   uptime_cycles_json.sha256          ✗   push-owned stream
#   cycle_history_jsonl.schema_sha256  ✗   GIT-TRACKED  ← the important one
#
# The first three are structural: those feeds are regenerated by host cron on
# their own cadence (deploy/feed-excludes.txt lists them as push-owned), so a
# pin taken at signing time is stale within minutes. Pinning a moving stream
# is a design problem, tracked separately as C4; this script does NOT try to
# fix it.
#
# The fourth is the one nobody could see. public/api/cycle-history.schema.v1.json
# is an ordinary git-tracked file that deploy delivers. A routine schema edit
# (7dfc3c4, 2026-08-05, "widen self-stake schema") changed its bytes and
# thereby silently invalidated a pin inside a manifest signed the day before.
# No CI job and no cron noticed. That is the failure mode this script closes:
# a normal commit must not be able to quietly break a signed manifest.
#
# ---------------------------------------------------------------------------
# What it does
# ---------------------------------------------------------------------------
# Enumerates every pin in .artifact_manifest (each entry contributes
# `<key>.sha256`, and `<key>.schema_sha256` when a schema is pinned),
# classifies each pin's target, compares the pinned digest against the real
# bytes, and applies a baseline so that only NEW breakage is red.
#
# Classification (single source of truth: deploy/feed-excludes.txt — the same
# file scripts/deploy/build-rsync-excludes.sh reads, so the two can never
# disagree about who owns a path):
#
#   stream   the target is listed in deploy/feed-excludes.txt = a
#            host-cron-written, push-owned feed that git never carries.
#            Its pin is expected to be stale. NEVER alerts, never fails.
#   tracked  everything else = a git-tracked file that deploy delivers, whose
#            bytes only change when a commit changes them. A stale pin here
#            means a commit broke the signed manifest. ALERTS and FAILS.
#
# Baseline (deploy/identity-pin-baseline.json): the pins already broken when
# this checker was introduced. A `tracked` mismatch is accepted (green) only
# when a baseline entry matches BOTH the current pinned digest AND the current
# observed digest. Change either side — re-sign the manifest, or edit the file
# again — and the baseline no longer applies, so the break is reported as new.
# The baseline is an acknowledgement of a known-open item, not a mute button.
#
# ---------------------------------------------------------------------------
# Repairing a red run (CI cannot do this for you)
# ---------------------------------------------------------------------------
# identity.json is signed with the operator's passphrase-protected ed25519 key
# on the operator's local Mac. CI has no access to it and must never have any,
# so CI can only detect and stop; the repair is manual. Two valid outcomes:
#
#   A. Do not change the pinned file. Revert the edit to the git-tracked
#      artifact and the pin is valid again.
#   B. Keep the change and re-issue the manifest:
#        1. land + deploy the artifact change so the live bytes are final
#        2. on the operator Mac:
#             export OPERATOR_IDENTITY_KEY=~/.ssh/freedom-yield-operator-identity
#             bash scripts/operator-local/gen-identity.sh
#           (at a cycle transition add FY_EXPECT_CYCLE=<just-closed cycle>)
#        3. commit public/api/identity.json + identity.json.sig
#        4. drop the now-obsolete entry from deploy/identity-pin-baseline.json
#           (this checker prints `OBSOLETE-BASELINE` lines naming them)
# See docs/OPERATOR_IDENTITY_SETUP.md § "Repairing a broken artifact pin".
#
# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
#   bash scripts/check-identity-pins.sh [--mode=repo|live] [--verbose]
#
#   --mode=repo  (default) compare the pins in the local
#                public/api/identity.json against the repo's own files.
#                This is the CI gate. `stream` pins are skipped outright:
#                git does not carry those files, so there is nothing to
#                compare and nothing a commit could have broken.
#   --mode=live  fetch the published identity.json and every pinned URL and
#                compare the served bytes. This is the ops monitor. Both
#                classes are compared, but only `tracked` breakage alerts.
#
# Exit codes:
#   0  no new breakage (pins match, or the only mismatches are baselined
#      `tracked` pins / structural `stream` pins)
#   2  cannot run — jq missing, identity manifest unreadable/unparseable/empty,
#      baseline unparseable, feed-excludes list unreadable, malformed pin URL,
#      no sha256 tool. In --mode=live every one of these also pushes (see
#      Alerting below); a blind checker must never be mistaken for a healthy one
#   3  NEW breakage on a `tracked` pin (mismatch, or the pinned file is gone)
#   4  --mode=live only: a `tracked` pin's URL could not be fetched, so the
#      comparison could not be made (mismatches are never masked by this —
#      a fetched 200 that mismatches is still exit 3)
#
# Alerting (--mode=live only):
#   A new `tracked` break fires ONE high-priority ntfy push via notify.sh.
#   `stream` mismatches and baselined `tracked` mismatches are written to the
#   log and never alert — they are known, structural, and pushing them would
#   be exactly the false urgency the project forbids.
#   EVERY exit-2 "cannot run" condition also pushes (via die() below). Under
#   cron the only channel is journald, so a silent exit 2 would look exactly
#   like a healthy run — the operator would read "no notification" as "pins
#   verified" while nothing was verified at all. Not deduped: exit 2 means the
#   checker is blind, which is not a state to grow quiet about.
#   Dedup: the alert signature is the sorted set of new breaks. The same
#   signature does not re-alert until $IDENTITY_PIN_ALERT_REARM_SEC has
#   elapsed (default 604800 = 7d, so a long-open break still nags weekly) or
#   the set changes. A green run clears the state, so a later break — even an
#   identical one — alerts immediately. Every input that feeds the dedup
#   decision fails OPEN (toward alerting): unreadable/unparseable state, a
#   non-numeric or future window epoch, and a non-numeric rearm setting all
#   bypass suppression.
#
# Env overrides:
#   FYD_REPO_ROOT       repo root (default: parent of this script's dir)
#   FYD_IDENTITY_FILE   local manifest path (repo mode)
#   FYD_IDENTITY_URL    published manifest URL (live mode)
#   FYD_BASELINE_FILE   baseline path (default deploy/identity-pin-baseline.json)
#   FYD_FEED_EXCLUDES   push-owned feed list (default deploy/feed-excludes.txt)
#   FYD_CURL            curl binary (tests substitute a stub)
#   FYD_NOTIFY          notifier (default <script dir>/notify.sh)
#   FYD_FETCH_ATTEMPTS  attempts per GET before giving up (default 3)
#   FYD_RETRY_SLEEP     seconds between attempts (default 3; tests use 0)
#   IDENTITY_PIN_LOG    file log (default <repo>/logs/identity-pin-drift.log)
#   IDENTITY_PIN_ALERT_STATE      dedup state file (default
#                       <repo>/logs/identity-pin-alert-state.json)
#   IDENTITY_PIN_ALERT_REARM_SEC  dedup re-arm window (default 604800)
#
# Cron target (/etc/cron.d/metal-identity-pins), daily 01:00 UTC = 10:00 JST
# (operator daytime — see the no-night-pings rule), installed by
# scripts/install-metal-identity-pins-cron.sh:
#   0 1 * * * deploy bash .../scripts/check-identity-pins.sh --mode=live 2>&1 | logger -t identity-pin-drift

set -uo pipefail

MODE=repo
VERBOSE=0
for arg in "$@"; do
	case "$arg" in
		--mode=repo|--mode=live) MODE="${arg#--mode=}" ;;
		--verbose|-v)            VERBOSE=1 ;;
		-h|--help)               sed -n '2,140p' "$0" | sed 's/^# \?//'; exit 0 ;;
		*) echo "ERROR: unknown arg: $arg (try --help)" >&2; exit 2 ;;
	esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${FYD_REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
IDENTITY_FILE="${FYD_IDENTITY_FILE:-${REPO_ROOT}/public/api/identity.json}"
IDENTITY_URL="${FYD_IDENTITY_URL:-https://metal.freedom-yield.com/api/identity.json}"
BASELINE_FILE="${FYD_BASELINE_FILE:-${REPO_ROOT}/deploy/identity-pin-baseline.json}"
FEED_EXCLUDES="${FYD_FEED_EXCLUDES:-${REPO_ROOT}/deploy/feed-excludes.txt}"
CURL="${FYD_CURL:-curl}"
NOTIFY="${FYD_NOTIFY:-${SCRIPT_DIR}/notify.sh}"
LOG="${IDENTITY_PIN_LOG:-${REPO_ROOT}/logs/identity-pin-drift.log}"
ALERT_STATE="${IDENTITY_PIN_ALERT_STATE:-${REPO_ROOT}/logs/identity-pin-alert-state.json}"
ALERT_REARM_SEC="${IDENTITY_PIN_ALERT_REARM_SEC:-604800}"
NOW_ISO="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

log() {
	printf '%s %s\n' "$NOW_ISO" "$*" >&2
	if [ -w "$(dirname "$LOG")" ] 2>/dev/null || [ -w "$LOG" ] 2>/dev/null; then
		printf '%s %s\n' "$NOW_ISO" "$*" >> "$LOG" 2>/dev/null || true
	fi
}

# alert <priority> <title> <message> — best-effort; a notify.sh failure is
# logged but never changes the caller's exit code (same contract as
# scripts/check-anchor-publish-health.sh).
alert() {
	if [ -x "$NOTIFY" ] || [ -f "$NOTIFY" ]; then
		bash "$NOTIFY" "$1" "$2" "$3" || log "WARN: notify failed (alert was: $2 — $3)"
	else
		log "WARN: notifier not found at $NOTIFY (alert was: $2 — $3)"
	fi
}

# die <message> — unrecoverable "cannot run" (exit 2). In live mode this MUST
# push, not merely log: the cron pipes its output to journald, so a silent
# exit 2 is indistinguishable from a clean run on the operator's phone —
# "no notification" would read as "healthy" at exactly the moment the checker
# stopped checking anything at all. check-anchor-publish-health.sh, the
# precedent this script follows elsewhere, already fires `alert high` on its
# own cannot-run condition (missing jq); leaving these paths silent would be
# an unexplained divergence from it, and inconsistent even within this file
# (the unfetchable-manifest path below alerts). Routing it through die()
# covers every cannot-run exit from one place. Repo mode deliberately does
# not push: there the non-zero exit already fails CI loudly and visibly.
die() {
	log "ERROR $*"
	if [ "$MODE" = "live" ]; then
		alert high "identity-pins: cannot run (exit 2)" "$*"
	fi
	exit 2
}

sha256_of_file() {
	if command -v shasum >/dev/null 2>&1; then
		shasum -a 256 "$1" 2>/dev/null | awk '{print $1}'
	elif command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" 2>/dev/null | awk '{print $1}'
	else
		echo ""
	fi
}

short() { printf '%s' "${1:0:12}"; }

command -v jq >/dev/null 2>&1 || die "jq not found — cannot read the artifact manifest"
[ -r "$FEED_EXCLUDES" ] || die "feed list not readable: $FEED_EXCLUDES (needed to classify pin targets)"

# ---- fetch with retry (live mode) -------------------------------------------
# Same shape as check-anchor-publish-health.sh's fetch(): stop at the first
# 200 so a transient cross-region blip does not read as breakage, and print
# exactly the final attempt's status code.
fetch() {
	local url="$1" outfile="$2"
	local attempts="${FYD_FETCH_ATTEMPTS:-3}"
	local sleep_s="${FYD_RETRY_SLEEP:-3}"
	local attempt=1 code
	while :; do
		code="$("$CURL" -sS -o "$outfile" -w "%{http_code}" --max-time 20 "$url" 2>/dev/null || echo "000")"
		[ "$code" = "200" ] && break
		[ "$attempt" -ge "$attempts" ] && break
		sleep "$sleep_s"
		attempt=$((attempt + 1))
	done
	printf '%s' "$code"
}

# ---- 1. load the manifest ----------------------------------------------------
TMP="$(mktemp -d "${TMPDIR:-/tmp}/identity-pins.XXXXXX")" || die "mktemp -d failed"
trap 'rm -rf "$TMP"' EXIT
MANIFEST_SRC="$TMP/identity.json"

if [ "$MODE" = "live" ]; then
	CODE="$(fetch "$IDENTITY_URL" "$MANIFEST_SRC")"
	[ "$CODE" = "200" ] || {
		log "ERROR identity manifest not served: $IDENTITY_URL HTTP=$CODE"
		alert high "identity-pins: manifest not served (exit 4)" "$IDENTITY_URL returned HTTP=$CODE — artifact pins could not be checked."
		exit 4
	}
else
	[ -r "$IDENTITY_FILE" ] || die "identity manifest not readable: $IDENTITY_FILE"
	cp "$IDENTITY_FILE" "$MANIFEST_SRC" || die "could not read $IDENTITY_FILE"
fi

jq empty "$MANIFEST_SRC" >/dev/null 2>&1 || die "identity manifest is not valid JSON (mode=$MODE)"

# One line per pin: "<pin_id>\t<url>\t<pinned_sha256>". Sorted for stable
# output and a stable alert signature.
PINS="$(jq -r '
	(.artifact_manifest // {}) | to_entries | sort_by(.key) | .[] |
	( if ((.value.url // "") != "" and (.value.sha256 // "") != "")
	  then "\(.key).sha256\t\(.value.url)\t\(.value.sha256)" else empty end ),
	( if ((.value.schema_url // "") != "" and (.value.schema_sha256 // "") != "")
	  then "\(.key).schema_sha256\t\(.value.schema_url)\t\(.value.schema_sha256)" else empty end )
' "$MANIFEST_SRC" 2>/dev/null)"

[ -n "$PINS" ] || die "identity manifest has no usable artifact_manifest pins (mode=$MODE)"

# ---- 2. load the baseline ----------------------------------------------------
BASELINE_JSON=""
if [ -e "$BASELINE_FILE" ]; then
	[ -r "$BASELINE_FILE" ] || die "baseline exists but is not readable: $BASELINE_FILE"
	BASELINE_JSON="$(jq -c '.' "$BASELINE_FILE" 2>/dev/null)" \
		|| die "baseline is not valid JSON: $BASELINE_FILE (refusing to run with an unreadable acknowledgement list)"
	[ -n "$BASELINE_JSON" ] || die "baseline is empty JSON: $BASELINE_FILE"
fi

# baseline_field <pin_id> <field> -> value or empty
baseline_field() {
	[ -n "$BASELINE_JSON" ] || return 0
	printf '%s' "$BASELINE_JSON" | jq -r --arg id "$1" --arg f "$2" \
		'(.known_broken[$id][$f]) // empty' 2>/dev/null
}

# ---- 3. classify a pin target ------------------------------------------------
# stream  = listed in deploy/feed-excludes.txt (push-owned feed, never in git)
# tracked = everything else (git-tracked, delivered by deploy)
classify_path() {
	local p="$1" line
	while IFS= read -r line || [ -n "$line" ]; do
		case "$line" in ''|\#*) continue ;; esac
		case "$line" in
			*/) [ "${p#"$line"}" != "$p" ] && { printf 'stream'; return 0; } ;;
			*)  [ "$p" = "$line" ] && { printf 'stream'; return 0; } ;;
		esac
	done < "$FEED_EXCLUDES"
	printf 'tracked'
}

# url_to_public_path <url> -> path relative to public/ (e.g. api/evidence.json)
url_to_public_path() {
	local u="$1" rest
	case "$u" in
		*://*) ;;
		*) return 1 ;;
	esac
	rest="${u#*://}"          # host/api/x.json
	case "$rest" in
		*/*) ;;
		*) return 1 ;;
	esac
	rest="${rest#*/}"         # api/x.json
	[ -n "$rest" ] || return 1
	printf '%s' "$rest"
}

# ---- 4. compare every pin ----------------------------------------------------
N_OK=0; N_BASELINED=0; N_STRUCTURAL=0; N_NEW=0; N_SKIP=0; N_FETCHFAIL=0; N_OBSOLETE=0
NEW_BREAKS=""
REPORT=""

emit() { REPORT="${REPORT}$1"$'\n'; }

while IFS=$'\t' read -r PIN_ID PIN_URL PIN_SHA; do
	[ -n "$PIN_ID" ] || continue
	REL="$(url_to_public_path "$PIN_URL")" \
		|| die "pin $PIN_ID has a malformed url: $PIN_URL"
	CLASS="$(classify_path "$REL")"

	ACTUAL=""
	if [ "$MODE" = "repo" ]; then
		if [ "$CLASS" = "stream" ]; then
			N_SKIP=$((N_SKIP + 1))
			emit "SKIP              ${PIN_ID}  stream   ${REL} is a push-owned feed — git carries no copy to compare"
			continue
		fi
		TARGET="${REPO_ROOT}/public/${REL}"
		if [ ! -f "$TARGET" ]; then
			N_NEW=$((N_NEW + 1))
			NEW_BREAKS="${NEW_BREAKS}${PIN_ID}:missing"$'\n'
			emit "MISSING           ${PIN_ID}  tracked  pinned=$(short "$PIN_SHA")… but public/${REL} does not exist"
			continue
		fi
		ACTUAL="$(sha256_of_file "$TARGET")"
		[ -n "$ACTUAL" ] || die "no sha256 tool available (need shasum or sha256sum)"
	else
		BODY="$TMP/body.$$"
		CODE="$(fetch "$PIN_URL" "$BODY")"
		if [ "$CODE" != "200" ]; then
			if [ "$CLASS" = "tracked" ]; then
				N_FETCHFAIL=$((N_FETCHFAIL + 1))
				emit "FETCH-FAIL        ${PIN_ID}  tracked  ${PIN_URL} HTTP=${CODE} — cannot verify"
			else
				emit "FETCH-FAIL        ${PIN_ID}  stream   ${PIN_URL} HTTP=${CODE} — not gated, informational"
			fi
			rm -f "$BODY"
			continue
		fi
		ACTUAL="$(sha256_of_file "$BODY")"
		rm -f "$BODY"
		[ -n "$ACTUAL" ] || die "no sha256 tool available (need shasum or sha256sum)"
	fi

	if [ "$ACTUAL" = "$PIN_SHA" ]; then
		N_OK=$((N_OK + 1))
		# Only `tracked` baseline entries gate anything, so only those can go
		# obsolete in a way the operator must act on. A `stream` entry is pure
		# documentation of a C4 target and a momentary match does not retire it.
		if [ "$(baseline_field "$PIN_ID" "class")" = "tracked" ]; then
			N_OBSOLETE=$((N_OBSOLETE + 1))
			emit "OBSOLETE-BASELINE ${PIN_ID}  ${CLASS}  pin now matches — delete this entry from ${BASELINE_FILE##*/}"
		fi
		[ "$VERBOSE" -eq 1 ] && emit "OK                ${PIN_ID}  ${CLASS}  $(short "$PIN_SHA")…"
		continue
	fi

	if [ "$CLASS" = "stream" ]; then
		# Structural by construction: a push-owned feed is rewritten by host
		# cron on its own cadence, so a pin captured at signing time is stale
		# within minutes. Recorded, never alerted. Resolved by C4 (stop
		# pinning moving streams), not by a notification.
		N_STRUCTURAL=$((N_STRUCTURAL + 1))
		emit "STRUCTURAL        ${PIN_ID}  stream   pinned=$(short "$PIN_SHA")… actual=$(short "$ACTUAL")… — expected drift, not gated (C4)"
		continue
	fi

	B_CLASS="$(baseline_field "$PIN_ID" "class")"
	B_PINNED="$(baseline_field "$PIN_ID" "pinned_sha256")"
	B_OBSERVED="$(baseline_field "$PIN_ID" "observed_sha256")"
	if [ "$B_CLASS" = "tracked" ] && [ "$B_PINNED" = "$PIN_SHA" ] && [ "$B_OBSERVED" = "$ACTUAL" ]; then
		N_BASELINED=$((N_BASELINED + 1))
		emit "BASELINED         ${PIN_ID}  tracked  pinned=$(short "$PIN_SHA")… actual=$(short "$ACTUAL")… — known-broken, acknowledged (C4)"
		continue
	fi

	N_NEW=$((N_NEW + 1))
	NEW_BREAKS="${NEW_BREAKS}${PIN_ID}:${PIN_SHA}:${ACTUAL}"$'\n'
	emit "MISMATCH          ${PIN_ID}  tracked  pinned=$(short "$PIN_SHA")… actual=$(short "$ACTUAL")… — NEW break of the signed manifest"
done <<EOF
${PINS}
EOF

printf '%s' "$REPORT"
echo "identity-pins summary (mode=${MODE}): ok=${N_OK} baselined=${N_BASELINED} structural=${N_STRUCTURAL} new=${N_NEW} skipped=${N_SKIP} fetch-fail=${N_FETCHFAIL} obsolete-baseline=${N_OBSOLETE}"

# ---- 5. alert dedup (live mode only) ----------------------------------------
# See "Alerting" in the header. Fails OPEN toward alerting on every
# untrustworthy input; a dedup bug must never silence a real break.
should_alert() {
	local sig="$1" now_epoch prev_sig prev_epoch
	now_epoch="$(date -u +%s)"
	[ -r "$ALERT_STATE" ] || { printf '1'; return 0; }
	[[ "$ALERT_REARM_SEC" =~ ^[0-9]+$ ]] || { printf '1'; return 0; }
	prev_sig="$(jq -r '.signature // empty' "$ALERT_STATE" 2>/dev/null || true)"
	prev_epoch="$(jq -r '.window_started_epoch // 0' "$ALERT_STATE" 2>/dev/null || echo 0)"
	[[ "$prev_epoch" =~ ^[0-9]+$ ]] || prev_epoch=0
	[ "$prev_epoch" -le "$now_epoch" ] || prev_epoch=0
	if [ -z "$prev_sig" ] || [ "$prev_sig" != "$sig" ]; then printf '1'; return 0; fi
	if [ $((now_epoch - prev_epoch)) -ge "$ALERT_REARM_SEC" ]; then printf '1'; return 0; fi
	printf '0'
}

state_write() {
	local sig="$1" now_epoch dir tmp
	now_epoch="$(date -u +%s)"
	dir="$(dirname "$ALERT_STATE")"
	mkdir -p "$dir" 2>/dev/null || true
	if [ ! -w "$dir" ] 2>/dev/null; then
		log "WARN: alert-dedup state dir not writable: $dir (state not persisted; next run will re-alert)"
		return 1
	fi
	tmp="$(mktemp "${dir}/.identity-pin-alert.XXXXXX" 2>/dev/null)" || {
		log "WARN: mktemp failed for alert-dedup state in $dir (state not persisted; next run will re-alert)"
		return 1
	}
	if ! jq -n --arg sig "$sig" --argjson epoch "$now_epoch" --arg iso "$NOW_ISO" \
		'{signature: $sig, window_started_epoch: $epoch, window_started_at: $iso}' > "$tmp" 2>/dev/null; then
		rm -f "$tmp"
		log "WARN: jq compose failed for alert-dedup state (state not persisted; next run will re-alert)"
		return 1
	fi
	mv "$tmp" "$ALERT_STATE" 2>/dev/null || {
		rm -f "$tmp"
		log "WARN: rename failed writing alert-dedup state to $ALERT_STATE (state not persisted; next run will re-alert)"
		return 1
	}
	return 0
}

if [ "$N_NEW" -gt 0 ]; then
	FIRST_LINE="$(printf '%s' "$REPORT" | grep -E '^(MISMATCH|MISSING) ' | head -1)"
	log "ERROR ${N_NEW} NEW artifact-pin break(s) in the signed identity manifest (mode=${MODE}): ${FIRST_LINE}"
	if [ "$MODE" = "live" ]; then
		SIG="$(printf '%s' "$NEW_BREAKS" | sort | tr '\n' ';')"
		if [ "$(should_alert "$SIG")" = "1" ]; then
			alert high "identity-pins: signed manifest broken (exit 3)" \
				"${N_NEW} git-tracked artifact pin(s) in the signed identity.json no longer match the published bytes. ${FIRST_LINE}. Re-issue the manifest (gen-identity.sh) or revert the artifact change — see docs/OPERATOR_IDENTITY_SETUP.md."
			state_write "$SIG"
		else
			log "INFO alert suppressed (dedup): same break set already alerted within the last ${ALERT_REARM_SEC}s — set IDENTITY_PIN_ALERT_REARM_SEC to override"
		fi
	fi
	exit 3
fi

if [ "$N_FETCHFAIL" -gt 0 ]; then
	log "WARN ${N_FETCHFAIL} tracked pin URL(s) unfetchable — pins could not be verified"
	if [ "$MODE" = "live" ]; then
		alert high "identity-pins: cannot verify (exit 4)" \
			"${N_FETCHFAIL} git-tracked pin URL(s) in identity.json could not be fetched after retries — artifact pins unverified."
	fi
	exit 4
fi

# Green: clear the dedup state so a later break — even an identical one —
# alerts immediately instead of being suppressed by a stale window.
[ "$MODE" = "live" ] && rm -f "$ALERT_STATE" 2>/dev/null
if [ "$VERBOSE" -eq 1 ]; then
	log "OK no new artifact-pin breakage (mode=${MODE}): ok=${N_OK} baselined=${N_BASELINED} structural=${N_STRUCTURAL}"
fi
exit 0
