#!/usr/bin/env bash
# check-identity-pins.sh — detect when the SIGNED artifact_manifest pins in
# public/api/identity.json stop describing reality.
#
# CHAIN: none — reads local files (--mode=repo) or performs read-only HTTP
#        GETs of public URLs (--mode=live). No broadcast, no push, no write
#        to any published artifact.
# PRIME_DIRECTIVE: TESTNET-FIRST — this script has no broadcast pathway.
#
# ---------------------------------------------------------------------------
# Why this exists
# ---------------------------------------------------------------------------
# identity.json carries an `artifact_manifest` object that pins the sha256 of
# every published artifact, and the whole manifest is ed25519-signed by the
# operator. The signature therefore asserts "these bytes are what we publish".
#
# On 2026-08-06 a measurement of the live site found 4 of the 8 pins already
# wrong, two days after the manifest was signed (90bcdd9, 2026-08-04):
#
#   evidence_json.sha256               ✗   push-owned stream
#   validator_json.sha256              ✗   push-owned stream
#   uptime_cycles_json.sha256          ✗   push-owned stream
#   cycle_history_jsonl.schema_sha256  ✗   GIT-TRACKED  ← the important one
#
# The first three are structural: those feeds are regenerated by host cron on
# their own cadence (deploy/feed-excludes.txt lists them as push-owned), so a
# pin taken at signing time is stale within minutes. Pinning a moving stream
# is a design problem: C4 fixed the GENERATOR (scripts/operator-local/
# gen-identity.sh reads deploy/publication.json and refuses to pin any
# kind=stream publication, landed 2026-08-14) and this script now enforces
# the same rule on whatever manifest is ALREADY signed — see "The kind gate"
# below. Neither repairs the manifest served today: it was signed before
# either existed, still pins the four rows above, and stays that way until
# the operator's next issuance (see "Repairing a red run" below).
#
# The fourth is the one nobody could see. public/api/cycle-history.schema.v1.json
# is an ordinary git-tracked file that deploy delivers. A routine schema edit
# (7dfc3c4, 2026-08-05, "widen self-stake schema") changed its bytes and
# thereby silently invalidated a pin inside a manifest signed the day before.
# No CI job and no cron noticed. That is the failure mode the MISMATCH check
# below closes: a normal commit must not be able to quietly break a signed
# manifest.
#
# ---------------------------------------------------------------------------
# What it does
# ---------------------------------------------------------------------------
# Enumerates every pin in .artifact_manifest (each entry contributes
# `<key>.sha256`, and `<key>.schema_sha256` when a schema is pinned), runs TWO
# independent checks against each one, and applies a baseline so that only
# NEW breakage of either kind is red.
#
# Check 1 — MISMATCH: does the pinned digest still match the real bytes?
# Classification for this check (single source of truth: deploy/feed-excludes.txt
# — the same file scripts/deploy/build-rsync-excludes.sh reads, so the two can
# never disagree about who owns a path):
#
#   stream   the target is listed in deploy/feed-excludes.txt = a
#            host-cron-written, push-owned feed that git never carries.
#            Its pin is expected to be stale. NEVER alerts, never fails.
#   tracked  everything else = a git-tracked file that deploy delivers, whose
#            bytes only change when a commit changes them. A stale pin here
#            means a commit broke the signed manifest. ALERTS and FAILS.
#
# Baseline (deploy/identity-pin-baseline.json): the pins already broken when
# this checker was introduced. A `tracked` mismatch is accepted (green) only
# when a baseline entry matches BOTH the current pinned digest AND the current
# observed digest. Change either side — re-sign the manifest, or edit the file
# again — and the baseline no longer applies, so the break is reported as new.
# The baseline is an acknowledgement of a known-open item, not a mute button.
#
# Check 2 — THE KIND GATE: may this pin exist at all, independent of whether
# its bytes currently match? Authority: deploy/publication.json's `kind` —
# the SAME registry scripts/operator-local/gen-identity.sh reads when
# composing a new manifest, so THIS checker's own kind resolution (below) has
# to agree with the generator's. Since 2026-08-17 that is machine-checked
# rather than intended: tests/publication-registry/'s T21 runs this script's
# resolution rule, the generator's, and its own, and fails on any
# disagreement. Note the exact scope for THIS script's copy — T21 extracts
# and runs only the jq PROGRAM between the T21-SENTINEL markers, not the
# shell function wrapped around it, so the `--arg p` wiring and the
# $REGISTRY_JSON feed below are outside what T21 sees (measured: breaking the
# --arg wiring leaves T21 green and is caught by tests/identity-pins/
# instead). See registry_kind_of() further down for how each copy is
# extracted. deploy/feed-excludes.txt is NOT the authority
# for this check: it is a narrower list (push-owned paths only) and carries
# no `kind` at all — api/archive/ is ON feed-excludes.txt (git never
# carries it) but is kind=record (safe to pin), which is exactly the
# distinction feed-excludes.txt cannot make.
#
#   kind=stream        MUST NOT be pinned (deploy/publication.json's own
#                       kind_definitions). Checked against
#                       deploy/publication.json's
#                       known_kind_violations.violations, keyed by the exact
#                       pin id (e.g. "evidence_json.sha256") — the SAME
#                       acknowledgement list
#                       tests/publication-registry/test-publication-registry.sh's
#                       T6/T7 hold to account, so there is exactly one place
#                       to acknowledge a known-open kind violation, not two.
#                         listed there   -> KIND-BASELINED, never alerts/fails
#                         not listed     -> KIND-VIOLATION, a NEW break
#                       Every entry in that list is separately checked for
#                       having EXPIRED and reported as OBSOLETE-KIND-ACK —
#                       see "Expiring the acknowledgement lists" below.
#   kind=record/static  pinnable; this check does nothing further (Check 1
#                       above still verifies the bytes).
#   no row at all       the checker cannot tell whether pinning this target
#                       is safe. Reported as KIND-UNKNOWN, a NEW break —
#                       unknown kind is never read as "probably fine", the
#                       same stance scripts/operator-local/gen-identity.sh
#                       takes when composing a manifest (an undeclared
#                       artifact is refused with exit 9, not guessed at).
#   anything else       a row EXISTS but its `kind` is not stream/static/
#                       record — a typo, or a future kind this checker does
#                       not yet know. Reported as KIND-INVALID, a NEW break.
#                       This is an ALLOWLIST (stream / static / record are
#                       the only recognized shapes), not "everything not
#                       stream is fine" — an earlier draft fell through
#                       silently here, which is exactly the fail-open this
#                       whole gate exists to prevent.
#
# The manifest currently served predates the kind gate entirely (see "Why
# this exists" above), so it still pins four kind=stream PAYLOAD pins: the
# three named there (evidence_json.sha256, validator_json.sha256,
# uptime_cycles_json.sha256) plus a fourth, cycle_history_jsonl.sha256 — NOT
# the same entry as cycle_history_jsonl.schema_sha256, the git-tracked
# SCHEMA mismatch "Why this exists" measured; that one is kind=static and
# this check does not touch it. All four payload pins are already
# acknowledged in deploy/publication.json's known_kind_violations, so this
# check is GREEN today. It stays green after the operator's next issuance
# removes those four pins, because there is then nothing left to gate. What
# it exists to catch is a FUTURE pin over a kind=stream (or undeclared)
# target that nobody acknowledged first — the exact way to re-break
# identity.json's artifact_manifest that Check 1 alone cannot see coming,
# because a brand new stream pin matches its own bytes at the moment it is
# taken.
#
# ---------------------------------------------------------------------------
# Expiring the acknowledgement lists (2026-08-17)
# ---------------------------------------------------------------------------
# Both lists exist to shrink to nothing, and neither is self-clearing. Each
# gets a report line when an entry stops describing anything real:
#
#   OBSOLETE-BASELINE  deploy/identity-pin-baseline.json — the pin it records
#                      as broken now matches.
#   OBSOLETE-KIND-ACK  deploy/publication.json's known_kind_violations — the
#                      pin no longer exists in the manifest, the entry's
#                      declared path is not what the manifest pins, or the
#                      target is no longer kind=stream. Same three conditions
#                      tests/publication-registry/'s T7 applies, so the two
#                      can never disagree about what "obsolete" means.
#
# BOTH are report-only: they do not change the exit code and they never push.
# An expired acknowledgement is housekeeping, not breakage — nothing is
# mis-pinned because a dead entry sits in a list, and failing on it would fail
# a run that is more correct than the one before it. T7 is the CI gate that
# does fail, inside the commit that leaves the entry behind, which is where
# the fix belongs. What this adds is the CRON path: T7 runs in CI only, so
# before this the daily live run could print KIND-BASELINED for entries that
# muted nothing, indefinitely and silently.
#
# Expected reading at the 2026-09-04 transition: today all four entries are
# real, so zero OBSOLETE-KIND-ACK lines. The moment step 4b of
# docs/CYCLE_GATE.md lands (violations set to {} in the same commit as the
# re-issued manifest) there are no entries left to expire, so still zero. The
# lines appear exactly in the window where one half of that commit landed
# without the other.
#
# ---------------------------------------------------------------------------
# Repairing a red run (CI cannot do this for you)
# ---------------------------------------------------------------------------
# identity.json is signed with the operator's passphrase-protected ed25519 key
# on the operator's local Mac. CI has no access to it and must never have any,
# so CI can only detect and stop; the repair is manual. Two valid outcomes:
#
#   A. Do not change the pinned file. Revert the edit to the git-tracked
#      artifact and the pin is valid again.
#   B. Keep the change and re-issue the manifest:
#        1. land + deploy the artifact change so the live bytes are final
#        2. on the operator Mac:
#             export OPERATOR_IDENTITY_KEY=~/.ssh/freedom-yield-operator-identity
#             bash scripts/operator-local/gen-identity.sh
#           (at a cycle transition add FY_EXPECT_CYCLE=<just-closed cycle>)
#        3. commit public/api/identity.json + identity.json.sig
#        4. drop the now-obsolete entry from deploy/identity-pin-baseline.json
#           (this checker prints `OBSOLETE-BASELINE` lines naming them)
# See docs/OPERATOR_IDENTITY_SETUP.md § "Repairing a broken artifact pin".
#
# Repairing a kind-gate break (exit 6) is a different decision: the manifest
# cannot fix its way to a safe pin by re-signing, because a kind=stream
# target really cannot be pinned. Valid outcomes:
#
#   A. The pin should not exist. Re-issue the manifest (step B above) —
#      gen-identity.sh's own C4 discipline never pins a kind=stream
#      publication, so the pin is simply absent from the next issuance.
#   B. It is a still-open, already-understood case (like the four rows named
#      in "Why this exists", before the operator's next issuance).
#      Acknowledge it in deploy/publication.json's
#      known_kind_violations.violations, keyed by the exact pin id this
#      checker's KIND-VIOLATION line names. This is the SAME list
#      tests/publication-registry/test-publication-registry.sh's T7 holds to
#      account, so acknowledging it there also satisfies T7.
#   C. KIND-UNKNOWN (no registry row at all): add a row for the publication
#      to deploy/publication.json's publications[] with the correct `kind`.
#      If that turns out to be `stream`, this becomes outcome A or B.
#   D. KIND-INVALID (a row exists but its `kind` is not stream/static/
#      record): fix the typo, or — if this is genuinely a new kind this
#      checker does not know yet — extend BOTH this script's allowlist
#      (the `case "$RKIND" in` below) and scripts/operator-local/
#      gen-identity.sh's kind_is_pinnable() in the same change. Never widen
#      one without the other; that is exactly the disagreement Check 2
#      exists to prevent. NOTE (2026-08-17): T21 machine-checks that the two
#      scripts RESOLVE a path to the same kind, but nothing yet checks that
#      the two PINNABILITY allowlists list the same kinds. Widening one
#      alone is still caught only by this instruction, not by a test.
#
# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
#   bash scripts/check-identity-pins.sh [--mode=repo|live] [--verbose]
#
#   --mode=repo  (default) compare the pins in the local
#                public/api/identity.json against the repo's own files.
#                This is the CI gate. `stream` pins are skipped outright:
#                git does not carry those files, so there is nothing to
#                compare and nothing a commit could have broken.
#   --mode=live  fetch the published identity.json and every pinned URL and
#                compare the served bytes. This is the ops monitor. Both
#                classes are compared, but only `tracked` breakage alerts.
#
# Exit codes:
#   0  no new breakage (pins match, or the only mismatches/kind-violations
#      are baselined `tracked` pins / structural `stream` pins / acknowledged
#      kind violations)
#   2  cannot run — jq missing, identity manifest unreadable/unparseable/empty,
#      baseline unparseable, feed-excludes list unreadable, publication
#      registry (deploy/publication.json, the kind-gate authority)
#      unreadable/unparseable/empty, malformed pin URL, no sha256 tool. In
#      --mode=live every one of these also pushes (see Alerting below); a
#      blind checker must never be mistaken for a healthy one
#   3  NEW breakage on a `tracked` pin (mismatch, or the pinned file is gone)
#   4  --mode=live only: a `tracked` pin's URL could not be fetched, so the
#      comparison could not be made (mismatches are never masked by this —
#      a fetched 200 that mismatches is still exit 3)
#   5  structural: scripts/lib/side-effects.sh is not readable. 5, not 3:
#      3 already means "a tracked pin broke" and renumbering it would lie to
#      every caller that branches on it (CI, the cron's log grep). 2 is also
#      taken, by "cannot run" conditions that ALERT — and alerting is exactly
#      what a missing side-effects library makes impossible.
#   6  NEW kind-gate break (Check 2, above): a pin exists over a kind=stream
#      publication that is not acknowledged in deploy/publication.json's
#      known_kind_violations, over a publication with no row in
#      deploy/publication.json at all, or over a row whose `kind` is none
#      of stream/static/record. The kind gate is evaluated, and this exit
#      is returned, BEFORE the exit-3/4 checks below: if a single run has
#      both a kind-gate break and a mismatch, 6 is what this run exits
#      with — but (--mode=live) the mismatch is NOT silently dropped: its
#      first line is folded into the SAME ntfy push text and into the
#      dedup signature (see Alerting below), specifically because under
#      cron the printed report reaches only journald and a mismatch that
#      never reaches ntfy is, to the operator, a mismatch that never
#      happened.
#
# Alerting (--mode=live only):
#   A new `tracked` break fires ONE high-priority ntfy push via notify.sh. A
#   new kind-gate break (exit 6) fires the same way, deduped by the same
#   signature/re-arm mechanism (should_alert below) as a mismatch break —
#   they share one dedup state file, so only ONE push fires per run even
#   when both a kind-gate break and a mismatch break are present at once.
#   That push is NOT kind-gate-only text, though: when a mismatch is also
#   present, its first line and its own break signature are folded into the
#   kind-gate push and into the dedup signature, so the operator still
#   learns about it from the single push this run sends, and the dedup
#   window re-arms if EITHER the kind break or the mismatch details change.
#   `stream` mismatches and baselined `tracked` mismatches are written to the
#   log and never alert — they are known, structural, and pushing them would
#   be exactly the false urgency the project forbids. The same is true of an
#   acknowledged (KIND-BASELINED) kind violation.
#   EVERY exit-2 "cannot run" condition also pushes (via die() below). Under
#   cron the only channel is journald, so a silent exit 2 would look exactly
#   like a healthy run — the operator would read "no notification" as "pins
#   verified" while nothing was verified at all. Not deduped: exit 2 means the
#   checker is blind, which is not a state to grow quiet about.
#   Dedup: the alert signature is the sorted set of new breaks. The same
#   signature does not re-alert until $IDENTITY_PIN_ALERT_REARM_SEC has
#   elapsed (default 604800 = 7d, so a long-open break still nags weekly) or
#   the set changes. A green run clears the state, so a later break — even an
#   identical one — alerts immediately. Every input that feeds the dedup
#   decision fails OPEN (toward alerting): unreadable/unparseable state, a
#   non-numeric or future window epoch, and a non-numeric rearm setting all
#   bypass suppression.
#
# FY_LIVE (C3 rollout 2026-08-06, scripts/lib/side-effects.sh)
#   Gates DELIVERY of the ntfy pushes above and the alert-dedup state writes
#   that pair with them — nothing else. Anything other than exactly "1" makes
#   each of those a loud dry no-op printing one "DRY: would …" line. The cron
#   env header carries FY_LIVE=1; tests deliberately do not.
#
#   THE VERDICT IS NEVER GATED. --mode=repo is the CI gate: it must return
#   the same exit code on a machine that has never heard of FY_LIVE, or CI
#   would go silently green the day this library landed — the exact "it went
#   quiet and nobody noticed" failure the rollout exists to prevent. Repo
#   mode has no push and no state write at all, so FY_LIVE changes nothing
#   about it; live mode still classifies, compares, logs and exits
#   identically, and only the push and the dedup record are suppressed.
#
#   The alert/state pairing is required by the library's contract: a dry
#   fyd_notify returns 0, so recording "already alerted" against a
#   notification nobody received would suppress the NEXT real alert for a
#   whole re-arm window. Both are gated by the same FY_LIVE, so they are
#   suppressed or performed together, never one without the other.
#
# Env overrides:
#   FYD_REPO_ROOT       repo root (default: parent of this script's dir)
#   FYD_IDENTITY_FILE   local manifest path (repo mode)
#   FYD_IDENTITY_URL    published manifest URL (live mode)
#   FYD_BASELINE_FILE   baseline path (default deploy/identity-pin-baseline.json)
#   FYD_FEED_EXCLUDES   push-owned feed list (default deploy/feed-excludes.txt)
#   FYD_REGISTRY        publication registry path (default
#                       deploy/publication.json) — the kind gate's authority
#                       on which publications may be pinned (Check 2, above)
#   FYD_CURL            curl binary (tests substitute a stub)
#   FYD_NOTIFY          notifier (default <script dir>/notify.sh). Resolved by
#                       scripts/lib/side-effects.sh, not here — the spelling
#                       and its precedence are unchanged.
#   FYD_FETCH_ATTEMPTS  attempts per GET before giving up (default 3)
#   FYD_RETRY_SLEEP     seconds between attempts (default 3; tests use 0)
#   IDENTITY_PIN_LOG    file log (default <repo>/logs/identity-pin-drift.log)
#   IDENTITY_PIN_ALERT_STATE      dedup state file (default
#                       <repo>/logs/identity-pin-alert-state.json)
#   IDENTITY_PIN_ALERT_REARM_SEC  dedup re-arm window (default 604800)
#
# Cron target (/etc/cron.d/metal-identity-pins), daily 01:00 UTC = 10:00 JST
# (operator daytime — see the no-night-pings rule), installed by
# scripts/install-metal-identity-pins-cron.sh:
#   0 1 * * * deploy bash .../scripts/check-identity-pins.sh --mode=live 2>&1 | logger -t identity-pin-drift

set -uo pipefail

MODE=repo
VERBOSE=0
for arg in "$@"; do
	case "$arg" in
		--mode=repo|--mode=live) MODE="${arg#--mode=}" ;;
		--verbose|-v)            VERBOSE=1 ;;
		# Print the header down to the "Usage" heading. Addressed by that
		# heading rather than by a line number: the literal `2,174p` this
		# replaced was already one edit away from truncating mid-sentence,
		# and did truncate the moment a section was added above it.
		-h|--help)               sed -n '2,/^# Usage$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
		*) echo "ERROR: unknown arg: $arg (try --help)" >&2; exit 2 ;;
	esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FYD_LIB="${SCRIPT_DIR}/lib/side-effects.sh"
if [ ! -r "$FYD_LIB" ]; then
	echo "check-identity-pins: FATAL: side-effects library not readable at $FYD_LIB" >&2
	exit 5
fi
# shellcheck source=scripts/lib/side-effects.sh
. "$FYD_LIB"

REPO_ROOT="${FYD_REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
IDENTITY_FILE="${FYD_IDENTITY_FILE:-${REPO_ROOT}/public/api/identity.json}"
IDENTITY_URL="${FYD_IDENTITY_URL:-https://metal.freedom-yield.com/api/identity.json}"
BASELINE_FILE="${FYD_BASELINE_FILE:-${REPO_ROOT}/deploy/identity-pin-baseline.json}"
FEED_EXCLUDES="${FYD_FEED_EXCLUDES:-${REPO_ROOT}/deploy/feed-excludes.txt}"
CURL="${FYD_CURL:-curl}"
LOG="${IDENTITY_PIN_LOG:-${REPO_ROOT}/logs/identity-pin-drift.log}"
ALERT_STATE="${IDENTITY_PIN_ALERT_STATE:-${REPO_ROOT}/logs/identity-pin-alert-state.json}"
ALERT_REARM_SEC="${IDENTITY_PIN_ALERT_REARM_SEC:-604800}"
NOW_ISO="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

log() {
	printf '%s %s\n' "$NOW_ISO" "$*" >&2
	if [ -w "$(dirname "$LOG")" ] 2>/dev/null || [ -w "$LOG" ] 2>/dev/null; then
		printf '%s %s\n' "$NOW_ISO" "$*" >> "$LOG" 2>/dev/null || true
	fi
}

# alert <priority> <title> <message> — best-effort; a notify.sh failure is
# logged but never changes the caller's exit code (same contract as
# scripts/check-anchor-publish-health.sh).
#
# Delivery is gated on FY_LIVE by fyd_notify; the delegate is resolved from
# FYD_NOTIFY exactly as before. A failure (including "delegate not readable",
# which used to be this function's own branch) is logged and swallowed.
alert() {
	fyd_notify "$1" "$2" "$3" || log "WARN: notify failed (alert was: $2 — $3)"
}

# die <message> — unrecoverable "cannot run" (exit 2). In live mode this MUST
# push, not merely log: the cron pipes its output to journald, so a silent
# exit 2 is indistinguishable from a clean run on the operator's phone —
# "no notification" would read as "healthy" at exactly the moment the checker
# stopped checking anything at all. check-anchor-publish-health.sh, the
# precedent this script follows elsewhere, already fires `alert high` on its
# own cannot-run condition (missing jq); leaving these paths silent would be
# an unexplained divergence from it, and inconsistent even within this file
# (the unfetchable-manifest path below alerts). Routing it through die()
# covers every cannot-run exit from one place. Repo mode deliberately does
# not push: there the non-zero exit already fails CI loudly and visibly.
die() {
	log "ERROR $*"
	if [ "$MODE" = "live" ]; then
		alert high "identity-pins: cannot run (exit 2)" "$*"
	fi
	exit 2
}

sha256_of_file() {
	if command -v shasum >/dev/null 2>&1; then
		shasum -a 256 "$1" 2>/dev/null | awk '{print $1}'
	elif command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" 2>/dev/null | awk '{print $1}'
	else
		echo ""
	fi
}

short() { printf '%s' "${1:0:12}"; }

command -v jq >/dev/null 2>&1 || die "jq not found — cannot read the artifact manifest"
[ -r "$FEED_EXCLUDES" ] || die "feed list not readable: $FEED_EXCLUDES (needed to classify pin targets)"

REGISTRY_FILE="${FYD_REGISTRY:-${REPO_ROOT}/deploy/publication.json}"
[ -r "$REGISTRY_FILE" ] || die "publication registry not readable: $REGISTRY_FILE (needed for the kind gate — deploy/publication.json is the authority on which publications may be pinned)"
REGISTRY_JSON="$(jq -c '.' "$REGISTRY_FILE" 2>/dev/null)" \
	|| die "publication registry is not valid JSON: $REGISTRY_FILE"
[ -n "$REGISTRY_JSON" ] || die "publication registry is empty JSON: $REGISTRY_FILE"

# ---- fetch with retry (live mode) -------------------------------------------
# Same shape as check-anchor-publish-health.sh's fetch(): stop at the first
# 200 so a transient cross-region blip does not read as breakage, and print
# exactly the final attempt's status code.
fetch() {
	local url="$1" outfile="$2"
	local attempts="${FYD_FETCH_ATTEMPTS:-3}"
	local sleep_s="${FYD_RETRY_SLEEP:-3}"
	local attempt=1 code
	while :; do
		code="$("$CURL" -sS -o "$outfile" -w "%{http_code}" --max-time 20 "$url" 2>/dev/null || echo "000")"
		[ "$code" = "200" ] && break
		[ "$attempt" -ge "$attempts" ] && break
		sleep "$sleep_s"
		attempt=$((attempt + 1))
	done
	printf '%s' "$code"
}

# ---- 1. load the manifest ----------------------------------------------------
TMP="$(mktemp -d "${TMPDIR:-/tmp}/identity-pins.XXXXXX")" || die "mktemp -d failed"
trap 'rm -rf "$TMP"' EXIT
MANIFEST_SRC="$TMP/identity.json"

if [ "$MODE" = "live" ]; then
	CODE="$(fetch "$IDENTITY_URL" "$MANIFEST_SRC")"
	[ "$CODE" = "200" ] || {
		log "ERROR identity manifest not served: $IDENTITY_URL HTTP=$CODE"
		alert high "identity-pins: manifest not served (exit 4)" "$IDENTITY_URL returned HTTP=$CODE — artifact pins could not be checked."
		exit 4
	}
else
	[ -r "$IDENTITY_FILE" ] || die "identity manifest not readable: $IDENTITY_FILE"
	cp "$IDENTITY_FILE" "$MANIFEST_SRC" || die "could not read $IDENTITY_FILE"
fi

jq empty "$MANIFEST_SRC" >/dev/null 2>&1 || die "identity manifest is not valid JSON (mode=$MODE)"

# One line per pin: "<pin_id>\t<url>\t<pinned_sha256>". Sorted for stable
# output and a stable alert signature.
PINS="$(jq -r '
	(.artifact_manifest // {}) | to_entries | sort_by(.key) | .[] |
	( if ((.value.url // "") != "" and (.value.sha256 // "") != "")
	  then "\(.key).sha256\t\(.value.url)\t\(.value.sha256)" else empty end ),
	( if ((.value.schema_url // "") != "" and (.value.schema_sha256 // "") != "")
	  then "\(.key).schema_sha256\t\(.value.schema_url)\t\(.value.schema_sha256)" else empty end )
' "$MANIFEST_SRC" 2>/dev/null)"

[ -n "$PINS" ] || die "identity manifest has no usable artifact_manifest pins (mode=$MODE)"

# ---- 2. load the baseline ----------------------------------------------------
BASELINE_JSON=""
if [ -e "$BASELINE_FILE" ]; then
	[ -r "$BASELINE_FILE" ] || die "baseline exists but is not readable: $BASELINE_FILE"
	BASELINE_JSON="$(jq -c '.' "$BASELINE_FILE" 2>/dev/null)" \
		|| die "baseline is not valid JSON: $BASELINE_FILE (refusing to run with an unreadable acknowledgement list)"
	[ -n "$BASELINE_JSON" ] || die "baseline is empty JSON: $BASELINE_FILE"
fi

# baseline_field <pin_id> <field> -> value or empty
baseline_field() {
	[ -n "$BASELINE_JSON" ] || return 0
	printf '%s' "$BASELINE_JSON" | jq -r --arg id "$1" --arg f "$2" \
		'(.known_broken[$id][$f]) // empty' 2>/dev/null
}

# ---- 3. classify a pin target ------------------------------------------------
# stream  = listed in deploy/feed-excludes.txt (push-owned feed, never in git)
# tracked = everything else (git-tracked, delivered by deploy)
classify_path() {
	local p="$1" line
	while IFS= read -r line || [ -n "$line" ]; do
		case "$line" in ''|\#*) continue ;; esac
		case "$line" in
			*/) [ "${p#"$line"}" != "$p" ] && { printf 'stream'; return 0; } ;;
			*)  [ "$p" = "$line" ] && { printf 'stream'; return 0; } ;;
		esac
	done < "$FEED_EXCLUDES"
	printf 'tracked'
}

# url_to_public_path <url> -> path relative to public/ (e.g. api/evidence.json)
#
# A fourth-and-a-half copy of this exists as scripts/operator-local/
# gen-identity.sh's url_to_registry_path(), and a jq spelling of the same
# conversion — sub("^https?://[^/]+/"; "") — is used inside two test suites.
# Reviewed 2026-08-17 (M-3) and deliberately NOT unified: the two bash copies
# live in scripts that must each run standalone and share no library, and the
# jq copies run INSIDE jq programs where a shell function cannot be called at
# all. What changed instead is that the agreement stopped being a claim:
# tests/publication-registry/'s T22 extracts BOTH bash copies by name and
# requires identical (exit status, stdout) on every probe URL, requires the
# jq SEMANTICS to agree with them on every URL the signed manifest actually
# carries (semantics only — T22 does not execute either jq copy; those are
# carried behaviourally by that suite's T7/T14 and by k8U in
# tests/identity-pins/), and holds the reason for keeping them apart to an
# expiry check.
# Refusing (return 1) on a URL with no path is the load-bearing behaviour
# here: the caller die()s on it rather than comparing against nothing.
url_to_public_path() {
	local u="$1" rest
	case "$u" in
		*://*) ;;
		*) return 1 ;;
	esac
	rest="${u#*://}"          # host/api/x.json
	case "$rest" in
		*/*) ;;
		*) return 1 ;;
	esac
	rest="${rest#*/}"         # api/x.json
	[ -n "$rest" ] || return 1
	printf '%s' "$rest"
}

# ---- kind gate (Check 2, see header) -----------------------------------------
# registry_kind_of <public-relative path> -> kind ("stream"/"record"/"static")
# or "" if no publications[] row governs it. Exact path match wins; otherwise
# a directory row (path ending "/") governs a member whose basename matches
# that row's member_pattern — the SAME resolution rule
# tests/publication-registry/test-publication-registry.sh's registry_row_for_path
# / kind_of applies. This is a HAND-COPY of that logic (a third one exists in
# scripts/operator-local/gen-identity.sh's registry_kind_of_path), which is
# itself the exact "正しい状態が1箇所に無い" pattern this whole task exists to
# close — reintroducing it here without a check would be the same mistake in
# a new place. tests/publication-registry/test-publication-registry.sh's T21
# closes it for all three: it extracts the jq program between the two
# T21-SENTINEL markers below VERBATIM (not a re-transcription), extracts
# gen-identity.sh's registry_kind_of_path() BY FUNCTION NAME and runs the
# generator's actual function, and requires both to return what that suite's
# OWN kind_of() returns for every path in the real registry plus directory
# members that do and do not match a member_pattern. An extraction that
# quietly stopped resolving anything FAILS rather than passes (the extracted
# text is shape- and content-checked before it is trusted), and the
# comparison is mutation-proved from both ends: doctoring the generator's
# resolver must be detected, and so must a regression in this suite's own
# reference. Until 2026-08-17 the
# generator's copy was a disclosed uncovered gap; it is the copy that
# composes a SIGNED manifest, so it was the last one that should have been
# running unchecked.
registry_kind_of() {
	printf '%s' "$REGISTRY_JSON" | jq -r --arg p "$1" '
		# T21-SENTINEL-BEGIN
		( [ .publications[] | select(.path == $p) | .kind ] | first // "" ) as $exact
		| if $exact != "" then $exact
		  else
			( [ .publications[]
				| . as $row
				| select($row.path | endswith("/"))
				| select(($row.member_pattern // "") != "")
				| select($p | startswith($row.path))
				| ($row.path | length) as $plen
				| ($p[$plen:]) as $member
				| select($member | test($row.member_pattern))
				| $row.kind
			  ] | first // "" )
		  end
		# T21-SENTINEL-END
	'
}

# known_kind_violation <pin_id> -> non-empty iff deploy/publication.json's
# known_kind_violations.violations acknowledges this exact pin id. The SAME
# acknowledgement list tests/publication-registry/test-publication-registry.sh's
# T6/T7 hold to account — one list, never two.
known_kind_violation() {
	printf '%s' "$REGISTRY_JSON" | jq -r --arg id "$1" '(.known_kind_violations.violations[$id]) // empty'
}

# ---- 4. compare every pin ----------------------------------------------------
N_OK=0; N_BASELINED=0; N_STRUCTURAL=0; N_NEW=0; N_SKIP=0; N_FETCHFAIL=0; N_OBSOLETE=0
N_KIND_BASELINED=0; N_KIND_NEW=0; N_KIND_OBSOLETE=0
NEW_BREAKS=""
KIND_NEW_BREAKS=""
REPORT=""

emit() { REPORT="${REPORT}$1"$'\n'; }

while IFS=$'\t' read -r PIN_ID PIN_URL PIN_SHA; do
	[ -n "$PIN_ID" ] || continue
	REL="$(url_to_public_path "$PIN_URL")" \
		|| die "pin $PIN_ID has a malformed url: $PIN_URL"
	CLASS="$(classify_path "$REL")"

	# ---- kind gate: may this pin exist at all? (independent of CLASS/MODE) --
	# ALLOWLIST, not a two-way if: "stream" and "" (no row) are the only
	# recognized non-pinnable shapes, and everything else used to fall
	# through silently — a typo'd or future-added kind value (e.g. "steam",
	# or a fifth kind this repo has not invented yet) passed the gate with
	# no check at all. Fixed to match scripts/operator-local/gen-identity.sh's
	# own allowlist shape (kind_is_pinnable: static|record, else refuse).
	RKIND="$(registry_kind_of "$REL")"
	case "$RKIND" in
		stream)
			if [ -n "$(known_kind_violation "$PIN_ID")" ]; then
				N_KIND_BASELINED=$((N_KIND_BASELINED + 1))
				emit "KIND-BASELINED    ${PIN_ID}  stream   ${REL} — kind=stream pin acknowledged in deploy/publication.json's known_kind_violations (C4)"
			else
				N_KIND_NEW=$((N_KIND_NEW + 1))
				KIND_NEW_BREAKS="${KIND_NEW_BREAKS}${PIN_ID}:kind=stream"$'\n'
				emit "KIND-VIOLATION    ${PIN_ID}  stream   ${REL} — kind=stream MUST NOT be pinned (deploy/publication.json) and is not acknowledged in known_kind_violations — NEW break"
			fi
			;;
		static|record)
			: # pinnable; Check 1 above still verifies the bytes.
			;;
		"")
			N_KIND_NEW=$((N_KIND_NEW + 1))
			KIND_NEW_BREAKS="${KIND_NEW_BREAKS}${PIN_ID}:kind=unresolved"$'\n'
			emit "KIND-UNKNOWN      ${PIN_ID}  ?        ${REL} has no publications[] row in deploy/publication.json — kind cannot be verified as safe to pin — NEW break"
			;;
		*)
			N_KIND_NEW=$((N_KIND_NEW + 1))
			KIND_NEW_BREAKS="${KIND_NEW_BREAKS}${PIN_ID}:kind=invalid:${RKIND}"$'\n'
			emit "KIND-INVALID      ${PIN_ID}  ${RKIND}   ${REL} — deploy/publication.json declares kind=\"${RKIND}\", which is none of stream/static/record — refusing to treat an unrecognized kind as safe to pin — NEW break"
			;;
	esac

	ACTUAL=""
	if [ "$MODE" = "repo" ]; then
		if [ "$CLASS" = "stream" ]; then
			N_SKIP=$((N_SKIP + 1))
			emit "SKIP              ${PIN_ID}  stream   ${REL} is a push-owned feed — git carries no copy to compare"
			continue
		fi
		TARGET="${REPO_ROOT}/public/${REL}"
		if [ ! -f "$TARGET" ]; then
			N_NEW=$((N_NEW + 1))
			NEW_BREAKS="${NEW_BREAKS}${PIN_ID}:missing"$'\n'
			emit "MISSING           ${PIN_ID}  tracked  pinned=$(short "$PIN_SHA")… but public/${REL} does not exist"
			continue
		fi
		ACTUAL="$(sha256_of_file "$TARGET")"
		[ -n "$ACTUAL" ] || die "no sha256 tool available (need shasum or sha256sum)"
	else
		BODY="$TMP/body.$$"
		CODE="$(fetch "$PIN_URL" "$BODY")"
		if [ "$CODE" != "200" ]; then
			if [ "$CLASS" = "tracked" ]; then
				N_FETCHFAIL=$((N_FETCHFAIL + 1))
				emit "FETCH-FAIL        ${PIN_ID}  tracked  ${PIN_URL} HTTP=${CODE} — cannot verify"
			else
				emit "FETCH-FAIL        ${PIN_ID}  stream   ${PIN_URL} HTTP=${CODE} — not gated, informational"
			fi
			rm -f "$BODY"
			continue
		fi
		ACTUAL="$(sha256_of_file "$BODY")"
		rm -f "$BODY"
		[ -n "$ACTUAL" ] || die "no sha256 tool available (need shasum or sha256sum)"
	fi

	if [ "$ACTUAL" = "$PIN_SHA" ]; then
		N_OK=$((N_OK + 1))
		# Only `tracked` baseline entries gate anything, so only those can go
		# obsolete in a way the operator must act on. A `stream` entry is pure
		# documentation of a C4 target and a momentary match does not retire it.
		if [ "$(baseline_field "$PIN_ID" "class")" = "tracked" ]; then
			N_OBSOLETE=$((N_OBSOLETE + 1))
			emit "OBSOLETE-BASELINE ${PIN_ID}  ${CLASS}  pin now matches — delete this entry from ${BASELINE_FILE##*/}"
		fi
		[ "$VERBOSE" -eq 1 ] && emit "OK                ${PIN_ID}  ${CLASS}  $(short "$PIN_SHA")…"
		continue
	fi

	if [ "$CLASS" = "stream" ]; then
		# Structural by construction: a push-owned feed is rewritten by host
		# cron on its own cadence, so a pin captured at signing time is stale
		# within minutes. Recorded, never alerted. Resolved by C4 (stop
		# pinning moving streams), not by a notification.
		N_STRUCTURAL=$((N_STRUCTURAL + 1))
		emit "STRUCTURAL        ${PIN_ID}  stream   pinned=$(short "$PIN_SHA")… actual=$(short "$ACTUAL")… — expected drift, not gated (C4)"
		continue
	fi

	B_CLASS="$(baseline_field "$PIN_ID" "class")"
	B_PINNED="$(baseline_field "$PIN_ID" "pinned_sha256")"
	B_OBSERVED="$(baseline_field "$PIN_ID" "observed_sha256")"
	if [ "$B_CLASS" = "tracked" ] && [ "$B_PINNED" = "$PIN_SHA" ] && [ "$B_OBSERVED" = "$ACTUAL" ]; then
		N_BASELINED=$((N_BASELINED + 1))
		emit "BASELINED         ${PIN_ID}  tracked  pinned=$(short "$PIN_SHA")… actual=$(short "$ACTUAL")… — known-broken, acknowledged (C4)"
		continue
	fi

	N_NEW=$((N_NEW + 1))
	NEW_BREAKS="${NEW_BREAKS}${PIN_ID}:${PIN_SHA}:${ACTUAL}"$'\n'
	emit "MISMATCH          ${PIN_ID}  tracked  pinned=$(short "$PIN_SHA")… actual=$(short "$ACTUAL")… — NEW break of the signed manifest"
done <<EOF
${PINS}
EOF

# ---- 4b. expire the kind acknowledgement list --------------------------------
# The mismatch side of this checker has always reported OBSOLETE-BASELINE when
# an entry in deploy/identity-pin-baseline.json stopped describing a real
# break. The kind side had no counterpart: known_kind_violations could go
# entirely stale — its pins re-signed away, its paths reclassified — and this
# checker would keep printing KIND-BASELINED for entries that mute nothing.
# tests/publication-registry/'s T7 does catch that, so CI has never been blind
# to it; the CRON path was, and would have stayed so permanently. Reported
# here for symmetry with OBSOLETE-BASELINE, and for the same reason: the
# acknowledgement lists are meant to shrink to nothing, and a list that is
# never told it has expired never does.
#
# Deliberately report-only — no exit code, no push:
#   - an expired acknowledgement is housekeeping, not breakage. Nothing is
#     mis-pinned because a dead entry sits in a list; the pin it named is
#     gone. Failing on it would fail a run that is MORE correct than the one
#     before it.
#   - T7 is already the gate that fails CI, and it fails inside the commit
#     that leaves the entry behind, which is where the fix belongs.
#   - pushing it would be exactly the false urgency this project forbids.
# Same three conditions T7 uses, so the two can never disagree about what
# "obsolete" means: the pin is gone, the declared path drifted away from the
# pin's real target, or the target is no longer kind=stream.
while IFS= read -r ACK_ID; do
	[ -n "$ACK_ID" ] || continue
	ACK_PATH="$(printf '%s' "$REGISTRY_JSON" | jq -r --arg id "$ACK_ID" '(.known_kind_violations.violations[$id].path) // ""')"
	ACK_URL="$(printf '%s\n' "$PINS" | awk -F'\t' -v k="$ACK_ID" '$1 == k { print $2; exit }')"
	if [ -z "$ACK_URL" ]; then
		N_KIND_OBSOLETE=$((N_KIND_OBSOLETE + 1))
		emit "OBSOLETE-KIND-ACK ${ACK_ID}  —  the signed manifest no longer carries this pin — delete the entry from ${REGISTRY_FILE##*/}'s known_kind_violations"
		continue
	fi
	ACK_REL="$(url_to_public_path "$ACK_URL" 2>/dev/null || true)"
	if [ -n "$ACK_PATH" ] && [ "$ACK_REL" != "$ACK_PATH" ]; then
		N_KIND_OBSOLETE=$((N_KIND_OBSOLETE + 1))
		emit "OBSOLETE-KIND-ACK ${ACK_ID}  —  acknowledges ${ACK_PATH} but the manifest pins ${ACK_REL} — the entry no longer describes the pin it mutes"
		continue
	fi
	ACK_KIND="$(registry_kind_of "$ACK_REL")"
	if [ "$ACK_KIND" != "stream" ]; then
		N_KIND_OBSOLETE=$((N_KIND_OBSOLETE + 1))
		emit "OBSOLETE-KIND-ACK ${ACK_ID}  —  ${ACK_REL} is kind=${ACK_KIND:-<no row>}, not stream: there is no violation left to acknowledge — delete the entry from ${REGISTRY_FILE##*/}'s known_kind_violations"
	fi
done <<EOF
$(printf '%s' "$REGISTRY_JSON" | jq -r '(.known_kind_violations.violations // {}) | keys[]' 2>/dev/null)
EOF

printf '%s' "$REPORT"
echo "identity-pins summary (mode=${MODE}): ok=${N_OK} baselined=${N_BASELINED} structural=${N_STRUCTURAL} new=${N_NEW} skipped=${N_SKIP} fetch-fail=${N_FETCHFAIL} obsolete-baseline=${N_OBSOLETE} kind-baselined=${N_KIND_BASELINED} kind-new=${N_KIND_NEW} obsolete-kind-ack=${N_KIND_OBSOLETE}"

# ---- 5. alert dedup (live mode only) ----------------------------------------
# See "Alerting" in the header. Fails OPEN toward alerting on every
# untrustworthy input; a dedup bug must never silence a real break.
should_alert() {
	local sig="$1" now_epoch prev_sig prev_epoch
	now_epoch="$(date -u +%s)"
	[ -r "$ALERT_STATE" ] || { printf '1'; return 0; }
	[[ "$ALERT_REARM_SEC" =~ ^[0-9]+$ ]] || { printf '1'; return 0; }
	prev_sig="$(jq -r '.signature // empty' "$ALERT_STATE" 2>/dev/null || true)"
	prev_epoch="$(jq -r '.window_started_epoch // 0' "$ALERT_STATE" 2>/dev/null || echo 0)"
	[[ "$prev_epoch" =~ ^[0-9]+$ ]] || prev_epoch=0
	[ "$prev_epoch" -le "$now_epoch" ] || prev_epoch=0
	if [ -z "$prev_sig" ] || [ "$prev_sig" != "$sig" ]; then printf '1'; return 0; fi
	if [ $((now_epoch - prev_epoch)) -ge "$ALERT_REARM_SEC" ]; then printf '1'; return 0; fi
	printf '0'
}

state_write() {
	local sig="$1" now_epoch dir tmp
	# FYD-GATE(branch): the whole body below is a durable state write that
	# records "the operator has been told about this break set". A dry
	# fyd_notify returned 0 without telling anybody, so recording it would
	# suppress the next REAL alert for a whole re-arm window — the library's
	# CONTRACT calls this out by name. Gate the record with the same FY_LIVE
	# that gated the notification, at the top, so no temp file is created
	# either.
	if ! fyd_is_live; then
		fyd_dry_note "record the identity-pin alert-dedup signature → ${ALERT_STATE}"
		return 0
	fi
	now_epoch="$(date -u +%s)"
	dir="$(dirname "$ALERT_STATE")"
	mkdir -p "$dir" 2>/dev/null || true
	if [ ! -w "$dir" ] 2>/dev/null; then
		log "WARN: alert-dedup state dir not writable: $dir (state not persisted; next run will re-alert)"
		return 1
	fi
	tmp="$(mktemp "${dir}/.identity-pin-alert.XXXXXX" 2>/dev/null)" || {
		log "WARN: mktemp failed for alert-dedup state in $dir (state not persisted; next run will re-alert)"
		return 1
	}
	if ! jq -n --arg sig "$sig" --argjson epoch "$now_epoch" --arg iso "$NOW_ISO" \
		'{signature: $sig, window_started_epoch: $epoch, window_started_at: $iso}' > "$tmp" 2>/dev/null; then
		rm -f "$tmp"
		log "WARN: jq compose failed for alert-dedup state (state not persisted; next run will re-alert)"
		return 1
	fi
	# FYD-GATE(branch): unreachable unless fyd_is_live returned true above.
	mv "$tmp" "$ALERT_STATE" 2>/dev/null || {
		rm -f "$tmp"
		log "WARN: rename failed writing alert-dedup state to $ALERT_STATE (state not persisted; next run will re-alert)"
		return 1
	}
	return 0
}

if [ "$N_KIND_NEW" -gt 0 ]; then
	FIRST_KIND_LINE="$(printf '%s' "$REPORT" | grep -E '^(KIND-VIOLATION|KIND-UNKNOWN|KIND-INVALID) ' | head -1)"
	log "ERROR ${N_KIND_NEW} NEW kind-gate break(s): a pin exists over a publication whose kind (deploy/publication.json) forbids pinning it, or whose kind could not be resolved at all (mode=${MODE}): ${FIRST_KIND_LINE}"
	# A concurrent tracked-pin mismatch (Check 1) is folded into THIS alert
	# rather than silently dropped: exit 6 is returned before the exit-3
	# block below ever runs, and both share one dedup state file, so without
	# this a mismatch that happens to coincide with a kind-gate break would
	# never reach ntfy — only the printed report, which under cron reaches
	# nobody but journald. See this file's own header, exit 6.
	MISMATCH_FOLD_MSG=""
	if [ "$N_NEW" -gt 0 ]; then
		FIRST_MISMATCH_LINE="$(printf '%s' "$REPORT" | grep -E '^(MISMATCH|MISSING) ' | head -1)"
		log "ERROR ${N_NEW} NEW mismatch break(s) ALSO present in this run (folded into the kind-gate alert below, not pushed as a separate exit-3 alert): ${FIRST_MISMATCH_LINE}"
		MISMATCH_FOLD_MSG=" ALSO: ${N_NEW} tracked-pin mismatch(es) in the same run — ${FIRST_MISMATCH_LINE}."
	fi
	if [ "$MODE" = "live" ]; then
		KIND_SIG="$(printf '%s' "$KIND_NEW_BREAKS" | sort | tr '\n' ';')"
		if [ "$N_NEW" -gt 0 ]; then
			MISMATCH_SIG="$(printf '%s' "$NEW_BREAKS" | sort | tr '\n' ';')"
			KIND_SIG="${KIND_SIG}||${MISMATCH_SIG}"
		fi
		if [ "$(should_alert "$KIND_SIG")" = "1" ]; then
			alert high "identity-pins: kind gate broken (exit 6)" \
				"${N_KIND_NEW} pin(s) in the signed identity.json target a publication deploy/publication.json marks kind=stream (must not be pinned), does not declare at all, or declares an unrecognized kind.${MISMATCH_FOLD_MSG} ${FIRST_KIND_LINE}. Acknowledge a still-open case in deploy/publication.json's known_kind_violations, fix the registry row, or re-issue the manifest — see docs/OPERATOR_IDENTITY_SETUP.md."
			state_write "$KIND_SIG"
		else
			log "INFO alert suppressed (dedup): same kind-break set already alerted within the last ${ALERT_REARM_SEC}s — set IDENTITY_PIN_ALERT_REARM_SEC to override"
		fi
	fi
	exit 6
fi

if [ "$N_NEW" -gt 0 ]; then
	FIRST_LINE="$(printf '%s' "$REPORT" | grep -E '^(MISMATCH|MISSING) ' | head -1)"
	log "ERROR ${N_NEW} NEW artifact-pin break(s) in the signed identity manifest (mode=${MODE}): ${FIRST_LINE}"
	if [ "$MODE" = "live" ]; then
		SIG="$(printf '%s' "$NEW_BREAKS" | sort | tr '\n' ';')"
		if [ "$(should_alert "$SIG")" = "1" ]; then
			alert high "identity-pins: signed manifest broken (exit 3)" \
				"${N_NEW} git-tracked artifact pin(s) in the signed identity.json no longer match the published bytes. ${FIRST_LINE}. Re-issue the manifest (gen-identity.sh) or revert the artifact change — see docs/OPERATOR_IDENTITY_SETUP.md."
			state_write "$SIG"
		else
			log "INFO alert suppressed (dedup): same break set already alerted within the last ${ALERT_REARM_SEC}s — set IDENTITY_PIN_ALERT_REARM_SEC to override"
		fi
	fi
	exit 3
fi

if [ "$N_FETCHFAIL" -gt 0 ]; then
	log "WARN ${N_FETCHFAIL} tracked pin URL(s) unfetchable — pins could not be verified"
	if [ "$MODE" = "live" ]; then
		alert high "identity-pins: cannot verify (exit 4)" \
			"${N_FETCHFAIL} git-tracked pin URL(s) in identity.json could not be fetched after retries — artifact pins unverified."
	fi
	exit 4
fi

# Green: clear the dedup state so a later break — even an identical one —
# alerts immediately instead of being suppressed by a stale window. Gated in
# lock step with state_write above: a dry run that cleared the window would
# make the NEXT dry run "re-alert" a notification nobody receives, and a dry
# run has no business mutating a file the live cron owns.
# Wrapped in a function so `2>/dev/null` stays on rm itself — a redirect
# written on the fyd_live_run call would belong to this shell and would also
# swallow the "DRY: would …" line the gate exists to print.
# FYD-GATE(branch): body reached only through the fyd_live_run below.
clear_alert_state() { rm -f "$ALERT_STATE" 2>/dev/null; }
if [ "$MODE" = "live" ]; then
	fyd_live_run "clear the identity-pin alert-dedup state at ${ALERT_STATE}" clear_alert_state
fi
if [ "$VERBOSE" -eq 1 ]; then
	log "OK no new artifact-pin breakage (mode=${MODE}): ok=${N_OK} baselined=${N_BASELINED} structural=${N_STRUCTURAL}"
fi
exit 0
