#!/usr/bin/env bash
# gen-evidence.sh — build a machine-readable evidence manifest for institutional readers.
#
# Purpose:
#   Combine the live validator state (NodeID / self-stake / delegation fee / status) with
#   the project's static commitments (non-custodial, renewal transparency, decommission
#   notice window, incident disclosure SLA) and the public-page URL set into a single
#   self-describing JSON file. Designed to be consumed by automated due-diligence tooling
#   on the reviewer side — one fetch, one parse, the whole evidence index.
#
# Dependencies:
#   jq only. No curl, no python. No new runtime dependencies.
#
# Inputs:
#   public/api/validator.json — live state, written every 5 minutes by scripts/node-info.sh.
#
# Output:
#   public/api/evidence.json — gitignored runtime artefact (see public/api/evidence.example.json
#   for the schema). Atomic write: same-directory tmp file + mv.
#
# Cron cadence:
#   Daily. The static parts change rarely and the live parts (node_id / self_stake / fee /
#   status) are already refreshed every 5 min into validator.json — running this once per
#   day is sufficient and well below any notion of "polite" load.
#
# Constraints (Constitution v0.1):
#   §4.2 C1   — No provider/region names in inputs or outputs.
#   §4.1      — No SSH paths, no host paths, no IPs, no credentials.
#   feedback_validator_operation_first — NO direct metalgo queries here. We only
#               re-read validator.json, which is the single canonical local artefact.
#   feedback_polite_external_access    — NO external API calls. Everything is local.
set -euo pipefail

REPO_BASE="${REPO_BASE:-$(cd "$(dirname "$0")/.." && pwd)}"
VALIDATOR_JSON="${REPO_BASE}/public/api/validator.json"
OUT="${REPO_BASE}/public/api/evidence.json"

if [[ ! -r "${VALIDATOR_JSON}" ]]; then
	echo "ERROR: ${VALIDATOR_JSON} not readable. Run scripts/node-info.sh first." >&2
	exit 1
fi

# Extract dynamic fields from validator.json.
#   - node_id:               .nodeId (string) or null.
#   - self_stake_metal:      .stake.self (number) or null.
#   - delegation_fee_percent .delegationFee.percent (number) or null.
#   - validator_status:      derived — "active" if nodeId present AND stake.self > 0
#                            AND all bootstrap chains true; otherwise "inactive".
NODE_ID=$(jq -r '.nodeId // empty' "${VALIDATOR_JSON}")
SELF_STAKE=$(jq -r '.stake.self // empty' "${VALIDATOR_JSON}")
FEE_PCT=$(jq -r '.delegationFee.percent // empty' "${VALIDATOR_JSON}")
P_BOOT=$(jq -r '.bootstrap.pChain // false' "${VALIDATOR_JSON}")
X_BOOT=$(jq -r '.bootstrap.xChain // false' "${VALIDATOR_JSON}")
C_BOOT=$(jq -r '.bootstrap.cChain // false' "${VALIDATOR_JSON}")

VALIDATOR_STATUS="inactive"
if [[ -n "${NODE_ID}" && -n "${SELF_STAKE}" && "${SELF_STAKE}" != "null" \
	&& "${P_BOOT}" == "true" && "${X_BOOT}" == "true" && "${C_BOOT}" == "true" ]]; then
	# Only flag active when stake is strictly positive.
	if awk -v v="${SELF_STAKE}" 'BEGIN { exit !(v + 0 > 0) }'; then
		VALIDATOR_STATUS="active"
	fi
fi

LAST_UPDATED=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Compose the manifest. Use jq so numeric/null typing is correct and the output is valid JSON.
TMP="$(dirname "${OUT}")/.evidence.json.tmp.$$"
trap 'rm -f "${TMP}"' EXIT

jq -n \
	--arg node_id "${NODE_ID}" \
	--arg status "${VALIDATOR_STATUS}" \
	--arg self_stake "${SELF_STAKE}" \
	--arg fee_pct "${FEE_PCT}" \
	--arg last_updated "${LAST_UPDATED}" \
	'{
		_comment: "Machine-readable evidence manifest for Freedom Yield Metal Blockchain validator. Generated by scripts/gen-evidence.sh from validator.json + static project config. The runtime file is gitignored; this example documents the schema.",
		brand: "Freedom Yield",
		network: "metal-mainnet",
		node_id: (if $node_id == "" then null else $node_id end),
		validator_status: $status,
		self_stake_metal: (if $self_stake == "" or $self_stake == "null" then null else ($self_stake | tonumber) end),
		delegation_fee_percent: (if $fee_pct == "" or $fee_pct == "null" then null else ($fee_pct | tonumber) end),
		public_pages: {
			status: "https://metal.freedom-yield.com/",
			uptime: "https://metal.freedom-yield.com/uptime/",
			incidents: "https://metal.freedom-yield.com/incidents/",
			commitments: "https://metal.freedom-yield.com/commitments/",
			risk_disclosure: "https://metal.freedom-yield.com/risk-disclosure/",
			jurisdiction: "https://metal.freedom-yield.com/jurisdiction/",
			selection_evidence: "https://metal.freedom-yield.com/selection-evidence/",
			data_catalog: "https://metal.freedom-yield.com/data/"
		},
		operator_commitments: {
			non_custodial: true,
			renewal_transparency: true,
			decommission_notice_days: 90,
			incident_disclosure_sla_hours: 24
		},
		explorer_url: "https://explorer.metalblockchain.org/",
		last_updated: $last_updated
	}' > "${TMP}"

mv "${TMP}" "${OUT}"
chmod 644 "${OUT}"
trap - EXIT

echo "Wrote ${OUT} (status=${VALIDATOR_STATUS}, node_id=${NODE_ID:-<empty>})"
