#!/bin/bash
# Push a file from this validator host (validator host) to the web host web host
# where Caddy serves it publicly.
#
# Allowed targets (must stay in lock-step with the case statement below):
#   validator.json              → /public/api/validator.json              (JSON-validated)
#   peer-geo.json               → /public/api/peer-geo.json               (JSON-validated)
#   uptime-recent.json          → /public/api/uptime-recent.json          (JSON-validated)
#   uptime-cycles.json          → /public/api/uptime-cycles.json          (JSON-validated)
#   peers.json                  → /public/api/peers.json                  (JSON-validated)
#   peers-changes.json          → /public/api/peers-changes.json          (JSON-validated)
#   peers-gini.json             → /public/api/peers-gini.json             (JSON-validated)
#   peers-gini-history.jsonl    → /public/api/peers-gini-history.jsonl    (JSONL)
#   peers-history-index.json    → /public/api/peers-history-index.json    (JSON-validated)
#   fee-market.json             → /public/api/fee-market.json             (JSON-validated)
#   fee-market-history.jsonl    → /public/api/fee-market-history.jsonl    (JSONL)
#   node-health-recent.json     → /public/api/node-health-recent.json     (JSON-validated)
#   evidence.json               → /public/api/evidence.json               (JSON-validated)
#   cycle-history.jsonl         → /public/api/cycle-history.jsonl         (JSONL)
#   anchor-receipt.json         → /public/api/anchor-receipt.json         (JSON-validated)
#   anchor-history.jsonl        → /public/api/anchor-history.jsonl        (JSONL)
#   schedule.ics                → /public/calendar/schedule.ics           (ICS-validated)
#   <16-64 hex>.ics             → /public/calendar/<name>.ics             (ICS-validated)
#
# Allowed SUBDIRECTORY targets (added 2026-08-05; exactly two prefixes, each
# with a strict basename pattern — anything else is rejected before ssh):
#   archive/anchor-source-<64 lowercase hex>.json
#                               → /public/api/archive/<basename>
#   archive/anchor-receipt-<64 lowercase hex>.json
#                               → /public/api/archive/<basename>
#   peers-history/peers-YYYY-MM-DD.json.gz
#                               → /public/api/peers-history/<basename>
#
# Why the subdirectory prefixes exist: anchor-history.jsonl publishes
# `archived_source_path` / `archived_receipt_path` pointing at
# `api/archive/…` (R18), and peers-history-index.json publishes snapshot
# names resolved by the public site as `/api/peers-history/<filename>`.
# Both were 404 because this script's allowlist was flat-filename-only and
# had no way to name a file inside a subdirectory, so the per-anchor
# archives and the daily peer snapshots never reached the web host at all.
#
# Note: server-status.json is excluded from the GitHub Actions deploy rsync but
# is not pushed through this wrapper — it's generated by a different mechanism.
#
# Background:
#   - Site is hosted on web host behind nginx + edge CDN.
#   - Live validator data is generated on this validator host by
#     node-info.sh / peer-geo.py. Calendar .ics generated by gen-renewal-ics.sh.
#   - This script ships freshly-generated files to web host.
#
# Security:
#   - Uses a dedicated ed25519 key (~/.ssh/web_push).
#   - web host's authorized_keys forces a wrapper that validates filename
#     against the same allowlist + content type before atomic mv.
#   - Every outbound byte is scanned by scripts/publish-guard.sh immediately
#     before it is handed to ssh (see scripts/lib/publish-scan.sh). The
#     allowlist above answers "may this NAME be published"; the scan answers
#     "may this CONTENT be published", which no allowlist can. Until
#     2026-08-06 nothing answered the second question on this path at all:
#     the guard's three existing layers all watch content on its way into
#     git, and every target here is gitignored and never touches git.
#
# Usage:
#   push-to-web-host.sh validator.json
#   push-to-web-host.sh peer-geo.json
#   push-to-web-host.sh <calendar-token>.ics
#   push-to-web-host.sh archive/anchor-receipt-<64hex>.json
#   push-to-web-host.sh peers-history/peers-2026-08-05.json.gz
set -euo pipefail

# Resolve repository root from script location if REPO_BASE is not set.
REPO_BASE="${REPO_BASE:-$(cd "$(dirname "$0")/.." && pwd)}"

FILENAME="${1:?usage: $0 <validator.json|peer-geo.json|evidence.json|cycle-history.jsonl|anchor-receipt.json|anchor-history.jsonl|<16-64hex>.ics|archive/<name>|peers-history/<name>>}"

# ---- fail-closed input sanitation (runs BEFORE allowlist dispatch) ------
# $FILENAME is not only used to build a local path — it is also handed to
# the remote sshd as the command string (SSH_ORIGINAL_COMMAND) that the web
# host's forced-command wrapper parses. So it must be rejected here for
# BOTH classes of abuse: local path escape, and remote command injection.
# These checks are deliberately independent of the allowlist below so that
# a future allowlist entry cannot accidentally admit a traversal shape.
case "$FILENAME" in
  *..*)
    echo "ERROR: path traversal rejected (filename contains '..'): $FILENAME" >&2
    exit 1
    ;;
  /*)
    echo "ERROR: absolute path rejected (filename must be relative): $FILENAME" >&2
    exit 1
    ;;
esac
# Shape: one optional subdirectory level, each component starting with an
# alphanumeric and containing only [A-Za-z0-9._-]. This rejects shell
# metacharacters, whitespace, control bytes, dotfiles, nested directories,
# and trailing slashes in a single expression.
if ! [[ "$FILENAME" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)?$ ]]; then
  echo "ERROR: illegal characters or shape in filename: $FILENAME" >&2
  exit 1
fi

# IMPORTANT: the web host runs an independent forced-command wrapper that
# also enforces its own allowlist (operator-local, out of this repo).
# Adding a filename here is only HALF the change — the operator must also
# add the same filename to the forced-command wrapper allowlist before
# pushes will succeed. The subdirectory prefixes below are installed on the
# web host by scripts/install-xserver-subdir-allowlist.sh, which ships the
# same two prefixes and the same basename patterns from
# scripts/deploy/receive-subdir-allowlist.snippet.sh. Keep the header
# comment, the case statement below, that snippet, and
# deploy/feed-excludes.txt in lock-step.
case "$FILENAME" in
  archive/*)
    # Per-anchor, content-addressed R18 archive copies written by
    # gen-anchor-source.sh / gen-anchor-receipt.sh into public/api/archive/.
    BASENAME="${FILENAME#archive/}"
    if ! [[ "$BASENAME" =~ ^anchor-(source|receipt)-[a-f0-9]{64}\.json$ ]]; then
      echo "ERROR: archive/ basename must be anchor-source-<64hex>.json or anchor-receipt-<64hex>.json (got: $BASENAME)" >&2
      exit 1
    fi
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/api/archive/${BASENAME}"
    ;;
  peers-history/*)
    # Daily gzipped full validator-set snapshots. The producer
    # (peer-validators.sh) writes these into the host state dir, NOT into
    # the repo — resolve there first, then fall back to a repo-local
    # staging copy so a backfill can be driven from either location.
    BASENAME="${FILENAME#peers-history/}"
    if ! [[ "$BASENAME" =~ ^peers-[0-9]{4}-[0-9]{2}-[0-9]{2}\.json\.gz$ ]]; then
      echo "ERROR: peers-history/ basename must be peers-YYYY-MM-DD.json.gz (got: $BASENAME)" >&2
      exit 1
    fi
    PEERS_HISTORY_DIR="${PEERS_HISTORY_DIR:-${UPTIME_STATE_DIR:-/var/lib/freedom-yield}/peers-history}"
    SOURCE="${PEERS_HISTORY_DIR}/${BASENAME}"
    if [ ! -f "$SOURCE" ]; then
      REPO_FALLBACK="${REPO_BASE:-/path/to/your/repo}/public/api/peers-history/${BASENAME}"
      if [ -f "$REPO_FALLBACK" ]; then
        SOURCE="$REPO_FALLBACK"
      else
        echo "ERROR: source not found: $SOURCE (nor repo fallback $REPO_FALLBACK)" >&2
        exit 1
      fi
    fi
    ;;
  validator.json|peer-geo.json|uptime-recent.json|uptime-cycles.json|peers.json|peers-changes.json|peers-gini.json|peers-gini-history.jsonl|peers-history-index.json|fee-market.json|fee-market-history.jsonl|node-health-recent.json|evidence.json|cycle-history.jsonl|anchor-receipt.json|anchor-history.jsonl)
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/api/${FILENAME}"
    ;;
  schedule.ics)
    # Public schedule mirror — discoverable URL for the "Subscribe in
    # Google Calendar" button on the website.
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/calendar/${FILENAME}"
    ;;
  *.ics)
    # Token-named .ics only (matches web host wrapper pattern).
    if ! [[ "$FILENAME" =~ ^[a-f0-9]{16,64}\.ics$ ]]; then
      echo "ERROR: ics filename must be 16-64 hex chars (got: $FILENAME)" >&2
      exit 1
    fi
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/calendar/${FILENAME}"
    ;;
  *)
    echo "ERROR: unrecognized filename: $FILENAME" >&2
    exit 1
    ;;
esac

# Host must be supplied out-of-band so the IP is never committed to the
# public repo. Two acceptable sources (env wins):
#   1. WEB_HOST env var, e.g. WEB_HOST=<deploy_user>@203.0.113.11
#   2. WEB_HOST_FILE env var pointing at an operator-local file
#      (default: /etc/freedom-yield/web-host — holds only the host, never
#       committed; the brand-namespaced PATH is public-safe, the value is not)
# Operator runbook is in operator-local notes.
HOST_FILE="${WEB_HOST_FILE:-/etc/freedom-yield/web-host}"
if [ -z "${WEB_HOST:-}" ] && [ -f "$HOST_FILE" ]; then
  WEB_HOST=$(tr -d "[:space:]" < "$HOST_FILE")
fi
: "${WEB_HOST:?WEB_HOST env var or ${HOST_FILE} is required}"
# SSH key path is operator-local; expose via env so the script doesn't bake
# in a specific file name.
KEY="${WEB_PUSH_KEY:-${HOME}/.ssh/web_push}"
TARGET="${WEB_HOST}"

[ -f "$SOURCE" ] || { echo "ERROR: source not found: $SOURCE" >&2; exit 1; }
[ -f "$KEY" ]    || { echo "ERROR: ssh key not found: $KEY" >&2; exit 1; }

# ---- outbound content scan (publish-guard, send-time layer) --------------
# Located from THIS SCRIPT's own directory, not from $REPO_BASE: REPO_BASE is
# a data root that callers and tests repoint at a fixture tree, and the send
# path must not be able to choose which guard polices it. A missing library is
# fatal for the same reason a missing guard is — see the fail-closed note in
# scripts/lib/publish-scan.sh.
PUBLISH_SCAN_LIB="$(cd "$(dirname "$0")" && pwd)/lib/publish-scan.sh"
if [ ! -r "$PUBLISH_SCAN_LIB" ]; then
  echo "ERROR: publish-scan library not found at $PUBLISH_SCAN_LIB" >&2
  echo "       Refusing to push ${FILENAME}: outbound content cannot be checked." >&2
  exit 1
fi
# shellcheck source=lib/publish-scan.sh
. "$PUBLISH_SCAN_LIB"
# Prove the guard still detects BEFORE trusting a clean verdict from it. Once
# per invocation, not once per retry.
fyd_publish_scan_selftest || {
  echo "ERROR: refusing to push ${FILENAME} — publish-guard could not be trusted (see above)." >&2
  exit 1
}

# Retry-with-backoff. web host's sshd default MaxStartups (10:30:100)
# combined with the constant brute-force flood on its public port means
# legitimate connections from us occasionally get caught in random-drop
# before authentication. a recent observation saw three consecutive
# pushes shot down this way, producing a 20-minute freshness alert.
#
# We retry up to 3 times with 5s / 15s backoff. Each attempt re-reads
# the source so a stale temp file doesn't get shipped if the producer
# rewrote it between attempts. Total worst-case latency: ~35s — still
# well under the 5-minute cron cadence.
#
# Each attempt snapshots the source, scans THE SNAPSHOT, and ships THE SAME
# SNAPSHOT. Scanning $SOURCE and then re-reading it for ssh would leave a
# window in which the producer (a 5-minute cron generator writing the same
# path) rewrites the file between the two reads, so the bytes that were
# checked and the bytes that were sent would not be the same bytes. The
# re-read-per-attempt behaviour above is preserved exactly: the snapshot is
# taken fresh inside the loop, so a retry still picks up a newer file — and
# now re-scans it, because a newer file is new content.
SNAPSHOT=""
# Always returns 0: this runs as an EXIT trap under `set -e`, where a non-zero
# return from the handler would be a second failure on top of whatever is
# already unwinding.
cleanup_snapshot() {
  if [ -n "$SNAPSHOT" ]; then rm -f "$SNAPSHOT"; fi
  SNAPSHOT=""
  return 0
}
# A signal handler MUST terminate the script. One handler registered for
# EXIT+HUP+INT+TERM does not: bash runs it and then CARRIES ON from wherever
# the signal interrupted. Measured on the first version of this block (30
# SIGTERM trials, no artificial delay): in 12 of them the handler had just set
# SNAPSHOT="" when the very next statement ran `cat "$SNAPSHOT" | ssh` — `cat`
# failed, but ssh still started and received an EMPTY stdin, i.e. a zero-byte
# body published under a real feed name. In the remainder the script simply
# absorbed the signal and ran all three attempts to completion, 19 s past the
# SIGTERM, so a cron timeout / `systemctl stop` / ^C could not stop a push.
# Exit codes are the conventional 128+signum so callers still see a signalled
# death. (This is not a leak path — the handler only deletes the snapshot, it
# never substitutes content, so the bytes are either the scanned ones or none.)
trap cleanup_snapshot EXIT
trap 'cleanup_snapshot; exit 129' HUP
trap 'cleanup_snapshot; exit 130' INT
trap 'cleanup_snapshot; exit 143' TERM

ATTEMPTS=3
DELAY=5
for i in $(seq 1 "$ATTEMPTS"); do
  SNAPSHOT="$(mktemp -t fyd-push.XXXXXX)" || {
    echo "ERROR: cannot create a temporary file to stage ${FILENAME}" >&2
    exit 1
  }
  if ! cat "$SOURCE" > "$SNAPSHOT"; then
    echo "ERROR: could not read source for ${FILENAME}: $SOURCE" >&2
    exit 1
  fi
  fyd_publish_scan_file "$SNAPSHOT" "$FILENAME" || {
    echo "ERROR: ${FILENAME} was NOT pushed — its content did not pass publish-guard." >&2
    exit 1
  }
  if cat "$SNAPSHOT" | ssh \
       -i "$KEY" \
       -o BatchMode=yes \
       -o ConnectTimeout=10 \
       -o StrictHostKeyChecking=yes \
       "$TARGET" \
       "$FILENAME"; then
    exit 0
  fi
  cleanup_snapshot
  if [ "$i" -lt "$ATTEMPTS" ]; then
    echo "push attempt ${i}/${ATTEMPTS} failed for ${FILENAME}, retrying in ${DELAY}s…" >&2
    sleep "$DELAY"
    DELAY=$(( DELAY * 3 ))
  fi
done
echo "ERROR: push failed for ${FILENAME} after ${ATTEMPTS} attempts" >&2
exit 1
