#!/bin/bash
# Push a file from this validator host (validator host) to the web host web host
# where Caddy serves it publicly.
#
# Allowed targets:
#   validator.json       → /public/api/validator.json     (JSON-validated)
#   peer-geo.json        → /public/api/peer-geo.json      (JSON-validated)
#   uptime-recent.json   → /public/api/uptime-recent.json (JSON-validated)
#   uptime-cycles.json   → /public/api/uptime-cycles.json (JSON-validated)
#   peers.json           → /public/api/peers.json         (JSON-validated)
#   <16-64 hex>.ics      → /public/calendar/<name>.ics    (ICS-validated)
#
# Background:
#   - Site is hosted on web host behind nginx + edge CDN.
#   - Live validator data is generated on this validator host by
#     node-info.sh / peer-geo.py. Calendar .ics generated by gen-renewal-ics.sh.
#   - This script ships freshly-generated files to web host.
#
# Security:
#   - Uses a dedicated ed25519 key (~/.ssh/web_push).
#   - web host's authorized_keys forces a wrapper that validates filename
#     against the same allowlist + content type before atomic mv.
#
# Usage:
#   push-to-web-host.sh validator.json
#   push-to-web-host.sh peer-geo.json
#   push-to-web-host.sh <calendar-token>.ics
set -euo pipefail

# Resolve repository root from script location if REPO_BASE is not set.
REPO_BASE="${REPO_BASE:-$(cd "$(dirname "$0")/.." && pwd)}"

FILENAME="${1:?usage: $0 <validator.json|peer-geo.json|<16-64hex>.ics>}"

case "$FILENAME" in
  validator.json|peer-geo.json|uptime-recent.json|uptime-cycles.json|peers.json|peers-changes.json|peers-gini.json|peers-gini-history.jsonl|peers-history-index.json|fee-market.json|fee-market-history.jsonl|node-health-recent.json)
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/api/${FILENAME}"
    ;;
  schedule.ics)
    # Public schedule mirror — discoverable URL for the "Subscribe in
    # Google Calendar" button on the website.
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/calendar/${FILENAME}"
    ;;
  *.ics)
    # Token-named .ics only (matches web host wrapper pattern).
    if ! [[ "$FILENAME" =~ ^[a-f0-9]{16,64}\.ics$ ]]; then
      echo "ERROR: ics filename must be 16-64 hex chars (got: $FILENAME)" >&2
      exit 1
    fi
    SOURCE="${REPO_BASE:-/path/to/your/repo}/public/calendar/${FILENAME}"
    ;;
  *)
    echo "ERROR: unrecognized filename: $FILENAME" >&2
    exit 1
    ;;
esac

# Host must be supplied out-of-band so the IP is never committed to the
# public repo. Two acceptable sources (env wins):
#   1. WEB_HOST env var, e.g. WEB_HOST=<deploy_user>@203.0.113.11
#   2. /etc/<your-namespace>/web-host file (whitespace-stripped contents)
# Operator runbook is in operator-local notes.
HOST_FILE="/etc/<your-namespace>/web-host"
if [ -z "${WEB_HOST:-}" ] && [ -f "$HOST_FILE" ]; then
  WEB_HOST=$(tr -d "[:space:]" < "$HOST_FILE")
fi
: "${WEB_HOST:?WEB_HOST env var or ${HOST_FILE} is required}"
KEY="${HOME}/.ssh/web_push"
TARGET="${WEB_HOST}"

[ -f "$SOURCE" ] || { echo "ERROR: source not found: $SOURCE" >&2; exit 1; }
[ -f "$KEY" ]    || { echo "ERROR: ssh key not found: $KEY" >&2; exit 1; }

# Retry-with-backoff. web host's sshd default MaxStartups (10:30:100)
# combined with the constant brute-force flood on its public port means
# legitimate connections from us occasionally get caught in random-drop
# before authentication. a recent observation saw three consecutive
# pushes shot down this way, producing a 20-minute freshness alert.
#
# We retry up to 3 times with 5s / 15s backoff. Each attempt re-reads
# the source so a stale temp file doesn't get shipped if the producer
# rewrote it between attempts. Total worst-case latency: ~35s — still
# well under the 5-minute cron cadence.
ATTEMPTS=3
DELAY=5
for i in $(seq 1 "$ATTEMPTS"); do
  if cat "$SOURCE" | ssh \
       -i "$KEY" \
       -o BatchMode=yes \
       -o ConnectTimeout=10 \
       -o StrictHostKeyChecking=yes \
       "$TARGET" \
       "$FILENAME"; then
    exit 0
  fi
  if [ "$i" -lt "$ATTEMPTS" ]; then
    echo "push attempt ${i}/${ATTEMPTS} failed for ${FILENAME}, retrying in ${DELAY}s…" >&2
    sleep "$DELAY"
    DELAY=$(( DELAY * 3 ))
  fi
done
echo "ERROR: push failed for ${FILENAME} after ${ATTEMPTS} attempts" >&2
exit 1
